--v233 奇观建造条件
DELETE FROM BuildingPrereqs WHERE Building='BUILDING_BIG_BEN';
DELETE FROM BuildingPrereqs WHERE Building='BUILDING_ESTADIO_DO_MARACANA';
DELETE FROM BuildingPrereqs WHERE Building='BUILDING_GREAT_LIBRARY';
DELETE FROM BuildingPrereqs WHERE Building='BUILDING_GREAT_LIGHTHOUSE';
DELETE FROM BuildingPrereqs WHERE Building='BUILDING_GREAT_ZIMBABWE';
DELETE FROM BuildingPrereqs WHERE Building='BUILDING_MAHABODHI_TEMPLE';
DELETE FROM BuildingPrereqs WHERE Building='BUILDING_OXFORD_UNIVERSITY';
-- DELETE FROM BuildingPrereqs WHERE Building='BUILDING_RUHR_VALLEY';v223删过
DELETE FROM BuildingPrereqs WHERE Building='BUILDING_TERRACOTTA_ARMY';
DELETE FROM BuildingPrereqs WHERE Building='BUILDING_KOTOKU_IN';
DELETE FROM BuildingPrereqs WHERE Building='BUILDING_AMUNDSEN_SCOTT_RESEARCH_STATION';
DELETE FROM BuildingPrereqs WHERE Building='BUILDING_UNIVERSITY_SANKORE';
DELETE FROM BuildingPrereqs WHERE Building='BUILDING_COLOSSEUM';
DELETE FROM BuildingPrereqs WHERE Building='BUILDING_STATUE_OF_ZEUS' AND EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_STATUE_OF_ZEUS');

--v236 远古奇观大修
DELETE FROM Building_YieldChanges WHERE BuildingType IN (SELECT BuildingType FROM Buildings WHERE ObsoleteEra="ERA_MEDIEVAL");
UPDATE Buildings SET Housing = 0, Entertainment = 0 WHERE BuildingType IN (SELECT BuildingType FROM Buildings WHERE ObsoleteEra="ERA_MEDIEVAL");
-- Hanging Garden 空中花园
-- 空中花园改英雄寿命是通过改property实现的，所以不存在兼容问题
INSERT OR REPLACE INTO Types (Type, Kind) VALUES 
('MODIFIER_PLAYER_CITIES_CULTURE_BORDER_EXPANSION', 'KIND_MODIFIER');
INSERT OR REPLACE INTO DynamicModifiers (ModifierType, CollectionType, EffectType) VALUES 
('MODIFIER_PLAYER_CITIES_CULTURE_BORDER_EXPANSION', 'COLLECTION_PLAYER_CITIES', 'EFFECT_ADJUST_CITY_CULTURE_BORDER_EXPANSION');

DELETE FROM BuildingModifiers WHERE BuildingType = 'BUILDING_HANGING_GARDENS';
INSERT OR REPLACE INTO BuildingModifiers
(BuildingType,		ModifierId)	VALUES
('BUILDING_HANGING_GARDENS',	'GOLDEN_HANGING_GARDENS_CITY_GROWTH'),
('BUILDING_HANGING_GARDENS',	'GOLDEN_HANGING_GARDENS_CITY_EXPANSION'),
('BUILDING_HANGING_GARDENS',	'GOLDEN_HANGING_GARDENS_HERO_LIFESPAN');

INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('GOLDEN_HANGING_GARDENS_CITY_GROWTH', 'MODIFIER_PLAYER_CITIES_ADJUST_CITY_GROWTH', 0, 0, 0, NULL, NULL),
('GOLDEN_HANGING_GARDENS_CITY_EXPANSION', 'MODIFIER_PLAYER_CITIES_CULTURE_BORDER_EXPANSION', 0, 0, 0, NULL, NULL),
('GOLDEN_HANGING_GARDENS_HERO_LIFESPAN', 'MODIFIER_PLAYER_ADJUST_PROPERTY', 0, 0, 0, NULL, NULL);

INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('GOLDEN_HANGING_GARDENS_CITY_GROWTH', 'Amount', 20),
('GOLDEN_HANGING_GARDENS_CITY_EXPANSION', 'Amount', 20),
('GOLDEN_HANGING_GARDENS_HERO_LIFESPAN', 'Key', 'PlayerHeroesExtraLifespan'),
('GOLDEN_HANGING_GARDENS_HERO_LIFESPAN', 'Amount', 10);

-- Temple Artemis 阿耳忒弥斯神庙
-- modifier是作用于三种改良上的
INSERT OR REPLACE INTO ImprovementModifiers
(ImprovementType,	ModifierId)	VALUES
('IMPROVEMENT_CAMP',		'GOLDEN_TEMPLE_ARTERMIS_CAMP_HOUSE'),
('IMPROVEMENT_PLANTATION',	'GOLDEN_TEMPLE_ARTERMIS_PLANTATION_HOUSE'),
('IMPROVEMENT_PASTURE',		'GOLDEN_TEMPLE_ARTERMIS_PASTURE_HOUSE');

INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('GOLDEN_TEMPLE_ARTERMIS_CAMP_HOUSE', 'MODIFIER_SINGLE_CITY_ADJUST_IMPROVEMENT_HOUSING', 0, 0, 0, NULL, 'TEMPLE_ARTEMIS_REQUIREMENTS'),
('GOLDEN_TEMPLE_ARTERMIS_PLANTATION_HOUSE', 'MODIFIER_SINGLE_CITY_ADJUST_IMPROVEMENT_HOUSING', 0, 0, 0, NULL, 'TEMPLE_ARTEMIS_REQUIREMENTS'),
('GOLDEN_TEMPLE_ARTERMIS_PASTURE_HOUSE', 'MODIFIER_SINGLE_CITY_ADJUST_IMPROVEMENT_HOUSING', 0, 0, 0, NULL, 'TEMPLE_ARTEMIS_REQUIREMENTS');

INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('GOLDEN_TEMPLE_ARTERMIS_CAMP_HOUSE', 'Amount', 1),
('GOLDEN_TEMPLE_ARTERMIS_PLANTATION_HOUSE', 'Amount', 1),
('GOLDEN_TEMPLE_ARTERMIS_PASTURE_HOUSE', 'Amount', 1);

-- Etemenanki 埃特曼安吉神庙
-- 来自葡萄牙包，同时还要使能在冻土泛滥上建造
INSERT OR REPLACE INTO Building_RequiredFeatures
(BuildingType,		FeatureType)	SELECT
'BUILDING_ETEMENANKI',	'FEATURE_FLOODPLAINS_TUNDRA'  WHERE EXISTS (SELECT Type FROM Types WHERE Type = 'FEATURE_FLOODPLAINS_TUNDRA') AND EXISTS (SELECT BuildingType FROM Buildings WHERE BuildingType = 'BUILDING_ETEMENANKI');

DELETE FROM BuildingModifiers WHERE BuildingType = 'BUILDING_ETEMENANKI';
INSERT OR REPLACE INTO BuildingModifiers
(BuildingType,		ModifierId)	SELECT
'BUILDING_ETEMENANKI',	'GOLDEN_ETEMENANKI_MARSH_SCIENCE'	WHERE EXISTS (SELECT BuildingType FROM Buildings WHERE BuildingType = 'BUILDING_ETEMENANKI');
INSERT OR REPLACE INTO BuildingModifiers
(BuildingType,		ModifierId)	SELECT
'BUILDING_ETEMENANKI',	'GOLDEN_ETEMENANKI_MARSH_CULTURE'	WHERE EXISTS (SELECT BuildingType FROM Buildings WHERE BuildingType = 'BUILDING_ETEMENANKI');
INSERT OR REPLACE INTO BuildingModifiers
(BuildingType,		ModifierId)	SELECT
'BUILDING_ETEMENANKI',	'GOLDEN_ETEMENANKI_FLOODPLAINS_PRODUCTION'	WHERE EXISTS (SELECT BuildingType FROM Buildings WHERE BuildingType = 'BUILDING_ETEMENANKI');

INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) SELECT
'GOLDEN_ETEMENANKI_MARSH_SCIENCE', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 0, 0, 0, NULL, 'GOLDEN_PLOT_HAS_MARSH_REQUIREMENTS'  WHERE EXISTS (SELECT BuildingType FROM Buildings WHERE BuildingType = 'BUILDING_ETEMENANKI');	
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) SELECT
'GOLDEN_ETEMENANKI_MARSH_CULTURE', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 0, 0, 0, NULL, 'GOLDEN_PLOT_HAS_MARSH_REQUIREMENTS'  WHERE EXISTS (SELECT BuildingType FROM Buildings WHERE BuildingType = 'BUILDING_ETEMENANKI');	
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) SELECT
'GOLDEN_ETEMENANKI_FLOODPLAINS_PRODUCTION', 'MODIFIER_PLAYER_ADJUST_PLOT_YIELD', 0, 0, 0, NULL, 'GA_PLOT_HAS_ANY_FLOODPLAINS_REQUIREMENTS'  WHERE EXISTS (SELECT BuildingType FROM Buildings WHERE BuildingType = 'BUILDING_ETEMENANKI');	

INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value) SELECT
'GOLDEN_ETEMENANKI_MARSH_SCIENCE', 'Amount', 2 WHERE EXISTS (SELECT BuildingType FROM Buildings WHERE BuildingType = 'BUILDING_ETEMENANKI');	
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value) SELECT
'GOLDEN_ETEMENANKI_MARSH_SCIENCE', 'YieldType', 'YIELD_SCIENCE' WHERE EXISTS (SELECT BuildingType FROM Buildings WHERE BuildingType = 'BUILDING_ETEMENANKI');
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value) SELECT
'GOLDEN_ETEMENANKI_MARSH_CULTURE', 'Amount', 2 WHERE EXISTS (SELECT BuildingType FROM Buildings WHERE BuildingType = 'BUILDING_ETEMENANKI');	
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value) SELECT
'GOLDEN_ETEMENANKI_MARSH_CULTURE', 'YieldType', 'YIELD_CULTURE' WHERE EXISTS (SELECT BuildingType FROM Buildings WHERE BuildingType = 'BUILDING_ETEMENANKI');
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value) SELECT
'GOLDEN_ETEMENANKI_FLOODPLAINS_PRODUCTION', 'Amount', 1 WHERE EXISTS (SELECT BuildingType FROM Buildings WHERE BuildingType = 'BUILDING_ETEMENANKI');	
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value) SELECT
'GOLDEN_ETEMENANKI_FLOODPLAINS_PRODUCTION', 'YieldType', 'YIELD_PRODUCTION' WHERE EXISTS (SELECT BuildingType FROM Buildings WHERE BuildingType = 'BUILDING_ETEMENANKI');


-- Great Bath 大浴场
-- 把大浴场全国化，同时兼容冻土泛滥
INSERT OR REPLACE INTO Types (Type, Kind) VALUES 
('MODIFIER_PLAYER_CITIES_ADJUST_YIELD_FOR_FLOOD', 'KIND_MODIFIER');
INSERT OR REPLACE INTO DynamicModifiers (ModifierType, CollectionType, EffectType) VALUES 
('MODIFIER_PLAYER_CITIES_ADJUST_YIELD_FOR_FLOOD', 'COLLECTION_PLAYER_CITIES', 'EFFECT_ADJUST_CITY_YIELD_PER_FLOOD');

INSERT OR REPLACE INTO Building_RequiredFeatures
(BuildingType,		FeatureType)	SELECT
'BUILDING_GREAT_BATH',	'FEATURE_FLOODPLAINS_TUNDRA'  WHERE EXISTS (SELECT Type FROM Types WHERE Type = 'FEATURE_FLOODPLAINS_TUNDRA');

DELETE FROM BuildingModifiers WHERE BuildingType = 'BUILDING_GREAT_BATH';
INSERT OR REPLACE INTO BuildingModifiers
(BuildingType,		ModifierId)	VALUES
('BUILDING_GREAT_BATH',	'GOLDEN_GREAT_BATH_FLOOD_FAITH');
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('GOLDEN_GREAT_BATH_FLOOD_FAITH', 'MODIFIER_PLAYER_CITIES_ADJUST_YIELD_FOR_FLOOD', 0, 0, 0, NULL, NULL);
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('GOLDEN_GREAT_BATH_FLOOD_FAITH', 'Amount', 1), 
('GOLDEN_GREAT_BATH_FLOOD_FAITH', 'YieldType', 'YIELD_FAITH');

-- Pyramids 金字塔
-- 需要兼容三种资源培育单位
DELETE FROM BuildingModifiers WHERE BuildingType = 'BUILDING_PYRAMIDS';
INSERT OR REPLACE INTO BuildingModifiers
(BuildingType,		ModifierId)	VALUES
('BUILDING_PYRAMIDS',	'GOLDEN_PYRAMIDS_ADJUST_BUILDER_AND_CULTIVATION_UNIT_CHARGES'),
('BUILDING_PYRAMIDS',   'GOLDEN_PYRAMIDS_ADJUST_BUILDER_AND_CULTIVATION_UNIT_MOVEMENT');
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('GOLDEN_PYRAMIDS_ADJUST_BUILDER_AND_CULTIVATION_UNIT_CHARGES', 'MODIFIER_PLAYER_UNITS_ADJUST_BUILDER_CHARGES', 0, 0, 0, NULL, 'GOLDEN_UNIT_IS_BUILDER_OR_CULTIVATION_UNIT_REQUIREMENTS'),
('GOLDEN_PYRAMIDS_ADJUST_BUILDER_AND_CULTIVATION_UNIT_MOVEMENT', 'MODIFIER_PLAYER_UNITS_ADJUST_MOVEMENT', 0, 0, 0, NULL, 'GOLDEN_UNIT_IS_BUILDER_OR_CULTIVATION_UNIT_REQUIREMENTS');
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('GOLDEN_PYRAMIDS_ADJUST_BUILDER_AND_CULTIVATION_UNIT_CHARGES', 'Amount', 1),
('GOLDEN_PYRAMIDS_ADJUST_BUILDER_AND_CULTIVATION_UNIT_MOVEMENT', 'Amount', 1);

INSERT OR REPLACE INTO RequirementSets (RequirementSetId, RequirementSetType) VALUES 
('GOLDEN_UNIT_IS_BUILDER_OR_CULTIVATION_UNIT_REQUIREMENTS', 'REQUIREMENTSET_TEST_ANY');

INSERT OR REPLACE INTO RequirementSetRequirements (RequirementSetId, RequirementId) VALUES 
('GOLDEN_UNIT_IS_BUILDER_OR_CULTIVATION_UNIT_REQUIREMENTS', 'GOLDEN_REQUIRE_UNIT_IS_BUILDER');
 INSERT OR REPLACE INTO RequirementSetRequirements (RequirementSetId, RequirementId) SELECT 
'GOLDEN_UNIT_IS_BUILDER_OR_CULTIVATION_UNIT_REQUIREMENTS', 'GOLDEN_REQUIRE_UNIT_IS_FARMER'  WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_HERDMAN');
INSERT OR REPLACE INTO RequirementSetRequirements (RequirementSetId, RequirementId) SELECT 
'GOLDEN_UNIT_IS_BUILDER_OR_CULTIVATION_UNIT_REQUIREMENTS', 'GOLDEN_REQUIRE_UNIT_IS_HERDMAN'  WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_HERDMAN');
INSERT OR REPLACE INTO RequirementSetRequirements (RequirementSetId, RequirementId) SELECT 
'GOLDEN_UNIT_IS_BUILDER_OR_CULTIVATION_UNIT_REQUIREMENTS', 'GOLDEN_REQUIRE_UNIT_IS_FISHER'  WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_HERDMAN');
INSERT OR REPLACE INTO RequirementSetRequirements (RequirementSetId, RequirementId) SELECT 
'GOLDEN_UNIT_IS_BUILDER_OR_CULTIVATION_UNIT_REQUIREMENTS', 'GOLDEN_REQUIRE_UNIT_IS_MINER'  WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_HERDMAN');

INSERT OR REPLACE INTO Requirements (RequirementId, RequirementType) VALUES 
('GOLDEN_REQUIRE_UNIT_IS_BUILDER', 'REQUIREMENT_UNIT_TYPE_MATCHES');
INSERT OR REPLACE INTO Requirements (RequirementId, RequirementType) SELECT
'GOLDEN_REQUIRE_UNIT_IS_FARMER', 'REQUIREMENT_UNIT_TYPE_MATCHES'  WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_HERDMAN');
INSERT OR REPLACE INTO Requirements (RequirementId, RequirementType) SELECT
'GOLDEN_REQUIRE_UNIT_IS_HERDMAN', 'REQUIREMENT_UNIT_TYPE_MATCHES'  WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_HERDMAN');
INSERT OR REPLACE INTO Requirements (RequirementId, RequirementType) SELECT
'GOLDEN_REQUIRE_UNIT_IS_FISHER', 'REQUIREMENT_UNIT_TYPE_MATCHES'  WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_HERDMAN');
INSERT OR REPLACE INTO Requirements (RequirementId, RequirementType) SELECT
'GOLDEN_REQUIRE_UNIT_IS_MINER', 'REQUIREMENT_UNIT_TYPE_MATCHES'  WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_HERDMAN');

INSERT OR REPLACE INTO RequirementArguments (RequirementId, Name, Value) VALUES 
('GOLDEN_REQUIRE_UNIT_IS_BUILDER', 'UnitType', 'UNIT_BUILDER');
INSERT OR REPLACE INTO RequirementArguments (RequirementId, Name, Value) SELECT
'GOLDEN_REQUIRE_UNIT_IS_FARMER', 'UnitType', 'UNIT_FARMER'	WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_HERDMAN');
INSERT OR REPLACE INTO RequirementArguments (RequirementId, Name, Value) SELECT
'GOLDEN_REQUIRE_UNIT_IS_HERDMAN', 'UnitType', 'UNIT_HERDMAN'	WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_HERDMAN');
INSERT OR REPLACE INTO RequirementArguments (RequirementId, Name, Value) SELECT
'GOLDEN_REQUIRE_UNIT_IS_FISHER', 'UnitType', 'UNIT_FISHER'	WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_HERDMAN');
INSERT OR REPLACE INTO RequirementArguments (RequirementId, Name, Value) SELECT
'GOLDEN_REQUIRE_UNIT_IS_MINER', 'UnitType', 'UNIT_MINER'	WHERE EXISTS (SELECT UnitType FROM Units WHERE UnitType = 'UNIT_HERDMAN');

-- Stone Henge 巨石阵
-- 原本效果实现麻烦，而且应该不会有mod改这种东西吧，就不删了
INSERT OR REPLACE INTO BuildingModifiers
(BuildingType,      ModifierId) VALUES
('BUILDING_STONEHENGE', 'GOLDEN_STONEHENGE_RELIGIOUS_SPREAD_STRENGTH'),
('BUILDING_STONEHENGE', 'GOLDEN_STONEHENGE_RELIGIOUS_SPREAD_DISTANCE');
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('GOLDEN_STONEHENGE_RELIGIOUS_SPREAD_STRENGTH', 'MODIFIER_PLAYER_RELIGION_ADJUST_RELIGIOUS_SPREAD_STRENGTH', 0, 0, 0, NULL, NULL),
('GOLDEN_STONEHENGE_RELIGIOUS_SPREAD_DISTANCE', 'MODIFIER_PLAYER_RELIGION_ADJUST_RELIGIOUS_SPREAD_DISTANCE', 0, 0, 0, NULL, NULL);
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('GOLDEN_STONEHENGE_RELIGIOUS_SPREAD_STRENGTH', 'EnhancingTechType', 0), 
('GOLDEN_STONEHENGE_RELIGIOUS_SPREAD_STRENGTH', 'SpreadMultiplier', 100),
('GOLDEN_STONEHENGE_RELIGIOUS_SPREAD_STRENGTH', 'TechEnabledSpreadMultiplier', 0),
('GOLDEN_STONEHENGE_RELIGIOUS_SPREAD_DISTANCE', 'DistanceChange', 5);

-- Oracle 神谕
-- 一大堆给英雄打折的就不删了
DELETE FROM BuildingModifiers WHERE BuildingType = 'BUILDING_ORACLE'  AND  (ModifierId NOT LIKE 'MODIFIER_ORACLE_RECALL%');
INSERT OR REPLACE INTO BuildingModifiers (BuildingType, ModifierId) VALUES 
('BUILDING_ORACLE', 'GOLDEN_ORACLE_GREATPERSON_FAITH_DISCOUNT'),
('BUILDING_ORACLE', 'GOLDEN_ORACLE_GREATGENERALPOINTS'),
('BUILDING_ORACLE', 'GOLDEN_ORACLE_GREATADMIRALPOINTS'),
('BUILDING_ORACLE', 'GOLDEN_ORACLE_GREATENGINEERPOINTS'),
('BUILDING_ORACLE', 'GOLDEN_ORACLE_GREATMERCHANTPOINTS'),
('BUILDING_ORACLE', 'GOLDEN_ORACLE_GREATPROPHETPOINTS'),
('BUILDING_ORACLE', 'GOLDEN_ORACLE_GREATSCIENTISTPOINTS'),
('BUILDING_ORACLE', 'GOLDEN_ORACLE_GREATWRITERPOINTS'),
('BUILDING_ORACLE', 'GOLDEN_ORACLE_GREATARTISTPOINTS'),
('BUILDING_ORACLE', 'GOLDEN_ORACLE_GREATMUSICIANPOINTS');
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, NewOnly, OwnerRequirementSetId, SubjectRequirementSetId) VALUES 
('GOLDEN_ORACLE_GREATPERSON_FAITH_DISCOUNT', 'MODIFIER_PLAYER_ADJUST_GREAT_PERSON_PATRONAGE_DISCOUNT_PERCENT', 0, 0, 0, NULL, NULL),
('GOLDEN_ORACLE_GREATGENERALPOINTS', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_GREAT_PERSON_POINTS', 0, 0, 0, NULL, 'DISTRICT_IS_ENCAMPMENT'),
('GOLDEN_ORACLE_GREATADMIRALPOINTS', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_GREAT_PERSON_POINTS', 0, 0, 0, NULL, 'DISTRICT_IS_HARBOR'),
('GOLDEN_ORACLE_GREATENGINEERPOINTS', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_GREAT_PERSON_POINTS', 0, 0, 0, NULL, 'DISTRICT_IS_INDUSTRIAL_ZONE'),
('GOLDEN_ORACLE_GREATMERCHANTPOINTS', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_GREAT_PERSON_POINTS', 0, 0, 0, NULL, 'DISTRICT_IS_COMMERCIAL_HUB'),
('GOLDEN_ORACLE_GREATPROPHETPOINTS', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_GREAT_PERSON_POINTS', 0, 0, 0, NULL, 'DISTRICT_IS_HOLY_SITE'),
('GOLDEN_ORACLE_GREATSCIENTISTPOINTS', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_GREAT_PERSON_POINTS', 0, 0, 0, NULL, 'DISTRICT_IS_CAMPUS'),
('GOLDEN_ORACLE_GREATWRITERPOINTS', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_GREAT_PERSON_POINTS', 0, 0, 0, NULL, 'DISTRICT_IS_THEATER'),
('GOLDEN_ORACLE_GREATARTISTPOINTS', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_GREAT_PERSON_POINTS', 0, 0, 0, NULL, 'DISTRICT_IS_THEATER'),
('GOLDEN_ORACLE_GREATMUSICIANPOINTS', 'MODIFIER_PLAYER_DISTRICTS_ADJUST_GREAT_PERSON_POINTS', 0, 0, 0, NULL, 'DISTRICT_IS_THEATER');
--英雄打折比例没有改成20%
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('GOLDEN_ORACLE_GREATPERSON_FAITH_DISCOUNT', 'Amount', 20), 
('GOLDEN_ORACLE_GREATPERSON_FAITH_DISCOUNT', 'YieldType', 'YIELD_FAITH'),
('GOLDEN_ORACLE_GREATGENERALPOINTS', 'Amount', 1),
('GOLDEN_ORACLE_GREATGENERALPOINTS', 'GreatPersonClassType', 'GREAT_PERSON_CLASS_GENERAL'),
('GOLDEN_ORACLE_GREATADMIRALPOINTS', 'Amount', 1),
('GOLDEN_ORACLE_GREATADMIRALPOINTS', 'GreatPersonClassType', 'GREAT_PERSON_CLASS_ADMIRAL'),
('GOLDEN_ORACLE_GREATENGINEERPOINTS', 'Amount', 1),
('GOLDEN_ORACLE_GREATENGINEERPOINTS', 'GreatPersonClassType', 'GREAT_PERSON_CLASS_ENGINEER'),
('GOLDEN_ORACLE_GREATMERCHANTPOINTS', 'Amount', 1),
('GOLDEN_ORACLE_GREATMERCHANTPOINTS', 'GreatPersonClassType', 'GREAT_PERSON_CLASS_MERCHANT'),
('GOLDEN_ORACLE_GREATPROPHETPOINTS', 'Amount', 1),
('GOLDEN_ORACLE_GREATPROPHETPOINTS', 'GreatPersonClassType', 'GREAT_PERSON_CLASS_PROPHET'),
('GOLDEN_ORACLE_GREATSCIENTISTPOINTS', 'Amount', 1),
('GOLDEN_ORACLE_GREATSCIENTISTPOINTS', 'GreatPersonClassType', 'GREAT_PERSON_CLASS_SCIENTIST'),
('GOLDEN_ORACLE_GREATWRITERPOINTS', 'Amount', 1),
('GOLDEN_ORACLE_GREATWRITERPOINTS', 'GreatPersonClassType', 'GREAT_PERSON_CLASS_WRITER'),
('GOLDEN_ORACLE_GREATARTISTPOINTS', 'Amount', 1),
('GOLDEN_ORACLE_GREATARTISTPOINTS', 'GreatPersonClassType', 'GREAT_PERSON_CLASS_ARTIST'),
('GOLDEN_ORACLE_GREATMUSICIANPOINTS', 'Amount', 1),
('GOLDEN_ORACLE_GREATMUSICIANPOINTS', 'GreatPersonClassType', 'GREAT_PERSON_CLASS_MUSICIAN');
