--v225 bug修复
UPDATE Units SET StrategicResource='RESOURCE_HORSES'
WHERE UnitType = 'UNIT_REITER';

--V230 费用调整
--远程
UPDATE Units SET Cost = 60
WHERE UnitType = 'UNIT_SLINGER';
UPDATE Units SET Cost = 120
WHERE UnitType = 'UNIT_ARCHER';
UPDATE Units SET Cost = 220
WHERE UnitType = 'UNIT_CROSSBOWMAN';
UPDATE Units SET Cost = 340
WHERE UnitType = 'UNIT_CULVERIN';
UPDATE Units SET Cost = 500
WHERE UnitType = 'UNIT_FIELD_CANNON';
UPDATE Units SET Cost = 700
WHERE UnitType = 'UNIT_HOWITZER';
UPDATE Units SET Cost = 900
WHERE UnitType = 'UNIT_MACHINE_GUN';
UPDATE Units SET Cost = 1100
WHERE UnitType = 'UNIT_MISSILE_VEHICLE';
--UU
UPDATE Units SET Cost = 60, Combat= 15, RangedCombat = 25
WHERE UnitType = 'UNIT_NUBIAN_PITATI' AND EXISTS (SELECT * FROM Units WHERE UnitType='UNIT_NUBIAN_PITATI');
UPDATE Units SET Cost = 60, Combat= 10, RangedCombat = 30
WHERE UnitType = 'UNIT_MAYAN_HULCHE' AND EXISTS (SELECT * FROM Units WHERE UnitType='UNIT_MAYAN_HULCHE');
UPDATE Units SET Cost = 220
WHERE UnitType = 'UNIT_CHINESE_CROUCHING_TIGER';
UPDATE Units SET Cost = 220
WHERE UnitType = 'UNIT_VIETNAMESE_VOI_CHIEN' AND EXISTS (SELECT * FROM Units WHERE UnitType='UNIT_VIETNAMESE_VOI_CHIEN');
UPDATE Units SET Cost = 340, Combat= 40
WHERE UnitType = 'UNIT_KOREAN_HWACHA';
--近战
UPDATE Units SET Cost = 40
WHERE UnitType = 'UNIT_WARRIOR';
UPDATE Units SET Cost = 80
WHERE UnitType = 'UNIT_SWORDSMAN';
UPDATE Units SET Cost = 160
WHERE UnitType = 'UNIT_MAN_AT_ARMS';
UPDATE Units SET Cost = 280
WHERE UnitType = 'UNIT_MUSKETMAN';
UPDATE Units SET Cost = 400
WHERE UnitType = 'UNIT_LINE_INFANTRY';
UPDATE Units SET Cost = 600
WHERE UnitType = 'UNIT_INFANTRY';
UPDATE Units SET Cost = 800
WHERE UnitType = 'UNIT_ELITE_INFANTRY';
UPDATE Units SET Cost = 1000
WHERE UnitType = 'UNIT_MECHANIZED_INFANTRY';
--UU
UPDATE Units SET Cost = 40, Combat = 32
WHERE UnitType = 'UNIT_AZTEC_EAGLE_WARRIOR' AND EXISTS (SELECT * FROM Units WHERE UnitType='UNIT_AZTEC_EAGLE_WARRIOR');
UPDATE Units SET Cost = 40, Combat = 30, BaseMoves = 2, BaseSightRange = 3
WHERE UnitType = 'UNIT_BABYLONIAN_SABUM_KIBITTUM' AND EXISTS (SELECT * FROM Units WHERE UnitType='UNIT_BABYLONIAN_SABUM_KIBITTUM');
UPDATE Units SET Cost = 40
WHERE UnitType = 'UNIT_GAUL_GAESATAE' AND EXISTS (SELECT * FROM Units WHERE UnitType='UNIT_GAUL_GAESATAE');
UPDATE Units SET Cost = 80, Combat = 42
WHERE UnitType = 'UNIT_ROMAN_LEGION';
UPDATE Units SET Cost = 80, Combat = 40
WHERE UnitType = 'UNIT_KONGO_SHIELD_BEARER';
UPDATE Units SET Cost = 80, Combat = 40
WHERE UnitType = 'UNIT_MAORI_TOA';
UPDATE Units SET Cost = 80, Combat = 40
WHERE UnitType = 'UNIT_MACEDONIAN_HYPASPIST' AND EXISTS (SELECT * FROM Units WHERE UnitType='UNIT_MACEDONIAN_HYPASPIST');
UPDATE Units SET Cost = 80
WHERE UnitType = 'UNIT_PERSIAN_IMMORTAL' AND EXISTS (SELECT * FROM Units WHERE UnitType='UNIT_PERSIAN_IMMORTAL');
UPDATE Units SET Cost = 160, Combat = 52
WHERE UnitType = 'UNIT_JAPANESE_SAMURAI';
UPDATE Units SET Cost = 280
WHERE UnitType = 'UNIT_SPANISH_CONQUISTADOR';
UPDATE Units SET Cost = 1, Combat = 60
WHERE UnitType = 'UNIT_SULEIMAN_JANISSARY';
UPDATE Units SET Cost = 400
WHERE UnitType = 'UNIT_ENGLISH_REDCOAT';
UPDATE Units SET Cost = 400
WHERE UnitType = 'UNIT_FRENCH_GARDE_IMPERIALE';
UPDATE Units SET Cost = 600
WHERE UnitType = 'UNIT_DIGGER' AND EXISTS (SELECT * FROM Units WHERE UnitType='UNIT_DIGGER');
--抗骑兵
UPDATE Units SET Cost = 40
WHERE UnitType = 'UNIT_SPEARMAN';
UPDATE Units SET Cost = 80
WHERE UnitType = 'UNIT_HEAVY_INFANTRY';
UPDATE Units SET Cost = 160
WHERE UnitType = 'UNIT_PIKEMAN';
UPDATE Units SET Cost = 280
WHERE UnitType = 'UNIT_PIKE_AND_SHOT';
UPDATE Units SET Cost = 400
WHERE UnitType = 'UNIT_ARQUEBUSIER';
UPDATE Units SET Cost = 600
WHERE UnitType = 'UNIT_AT_CREW';
UPDATE Units SET Cost = 800
WHERE UnitType = 'UNIT_MODERN_AT';
UPDATE Units SET Cost = 1000
WHERE UnitType = 'UNIT_AT_MISSILE';
--UU
UPDATE Units SET Cost = 80, Combat = 48
WHERE UnitType = 'UNIT_ZULU_IMPI';
UPDATE Units SET Cost = 400, Combat = 65
WHERE UnitType = 'UNIT_SWEDEN_CAROLEAN';
--攻城
UPDATE Units SET Cost = 160
WHERE UnitType = 'UNIT_CATAPULT';
UPDATE Units SET Cost = 280
WHERE UnitType = 'UNIT_TREBUCHET';
UPDATE Units SET Cost = 400
WHERE UnitType = 'UNIT_BOMBARD';
UPDATE Units SET Cost = 600
WHERE UnitType = 'UNIT_RIFLED_CANNON';
UPDATE Units SET Cost = 800
WHERE UnitType = 'UNIT_ARTILLERY';
UPDATE Units SET Cost = 1000
WHERE UnitType = 'UNIT_ATOMIC_ARTILLERY';
UPDATE Units SET Cost = 1200
WHERE UnitType = 'UNIT_ROCKET_ARTILLERY';
--UU
UPDATE Units SET Cost = 280
WHERE UnitType = 'UNIT_KHMER_DOMREY' AND EXISTS (SELECT * FROM Units WHERE UnitType='UNIT_KHMER_DOMREY');
--重骑兵
UPDATE Units SET Cost = 80
WHERE UnitType = 'UNIT_HEAVY_CHARIOT';
UPDATE Units SET Cost = 160
WHERE UnitType = 'UNIT_ARMORED_HORSEMAN';
UPDATE Units SET Cost = 280
WHERE UnitType = 'UNIT_KNIGHT';
UPDATE Units SET Cost = 400
WHERE UnitType = 'UNIT_REITER';
UPDATE Units SET Cost = 600
WHERE UnitType = 'UNIT_CUIRASSIER';
UPDATE Units SET Cost = 800
WHERE UnitType = 'UNIT_LANDSHIP';
UPDATE Units SET Cost = 1000
WHERE UnitType = 'UNIT_TANK';
UPDATE Units SET Cost = 1200
WHERE UnitType = 'UNIT_MODERN_ARMOR';
--UU
UPDATE Units SET Cost = 80, Combat = 32
WHERE UnitType = 'UNIT_SUMERIAN_WAR_CART';
UPDATE Units SET Cost = 160, Combat = 45
WHERE UnitType = 'UNIT_INDIAN_VARU';
UPDATE Units SET Cost = 160, Combat = 42
WHERE UnitType = 'UNIT_MACEDONIAN_HETAIROI' AND EXISTS (SELECT * FROM Units WHERE UnitType='UNIT_MACEDONIAN_HETAIROI');
UPDATE Units SET Cost = 280, Combat = 52
WHERE UnitType = 'UNIT_ARABIAN_MAMLUK';
UPDATE Units SET Cost = 280, Combat = 55
WHERE UnitType = 'UNIT_MALI_MANDEKALU_CAVALRY';
UPDATE Units SET Cost = 280, Combat = 52
WHERE UnitType = 'UNIT_BYZANTINE_TAGMA' AND EXISTS (SELECT * FROM Units WHERE UnitType='UNIT_BYZANTINE_TAGMA');
UPDATE Units SET Cost = 400
WHERE UnitType = 'UNIT_POLISH_HUSSAR' AND EXISTS (SELECT * FROM Units WHERE UnitType='UNIT_POLISH_HUSSAR');
UPDATE Units SET Cost = 600
WHERE UnitType = 'UNIT_AMERICAN_ROUGH_RIDER';
--轻骑兵
UPDATE Units SET Cost = 120
WHERE UnitType = 'UNIT_HORSEMAN';
UPDATE Units SET Cost = 220
WHERE UnitType = 'UNIT_COURSER';
UPDATE Units SET Cost = 340
WHERE UnitType = 'UNIT_DRAGOON';
UPDATE Units SET Cost = 500
WHERE UnitType = 'UNIT_CAVALRY';
UPDATE Units SET Cost = 700
WHERE UnitType = 'UNIT_CARABINIER';
UPDATE Units SET Cost = 900
WHERE UnitType = 'UNIT_HELICOPTER';
UPDATE Units SET Cost = 1100
WHERE UnitType = 'UNIT_SUPER_HELICOPTER';
--UU
UPDATE Units SET Cost = 220
WHERE UnitType = 'UNIT_HUNGARY_BLACK_ARMY';
UPDATE Units SET Cost = 220
WHERE UnitType = 'UNIT_ETHIOPIAN_OROMO_CAVALRY' AND EXISTS (SELECT * FROM Units WHERE UnitType='UNIT_ETHIOPIAN_OROMO_CAVALRY');
UPDATE Units SET Cost = 340, Combat = 57, BaseMoves = 5
WHERE UnitType = 'UNIT_MAPUCHE_MALON_RAIDER';
UPDATE Units SET Cost = 500, Combat = 66
WHERE UnitType = 'UNIT_COLOMBIAN_LLANERO' AND EXISTS (SELECT * FROM Units WHERE UnitType='UNIT_COLOMBIAN_LLANERO');
UPDATE Units SET Cost = 500, Combat = 67
WHERE UnitType = 'UNIT_HUNGARY_HUSZAR';
UPDATE Units SET Cost = 500, Combat = 70
WHERE UnitType = 'UNIT_RUSSIAN_COSSACK';
UPDATE Units SET Cost = 700
WHERE UnitType = 'UNIT_CANADA_MOUNTIE';
--侦察
UPDATE Units SET Cost = 40, Combat= 22, RangedCombat = 0, BaseMoves = 3, BaseSightRange = 3, Range = 0
WHERE UnitType = 'UNIT_SCOUT';
UPDATE Units SET Cost = 160, Combat= 42, RangedCombat = 0, BaseMoves = 4, BaseSightRange = 4, Range = 0
WHERE UnitType = 'UNIT_SKIRMISHER';
UPDATE Units SET Cost = 400, Combat= 62, RangedCombat = 0, BaseMoves = 5, BaseSightRange = 5, Range = 0
WHERE UnitType = 'UNIT_RANGER';
UPDATE Units SET Cost = 800, Combat= 82, RangedCombat = 0, BaseMoves = 6, BaseSightRange = 6, Range = 0
WHERE UnitType = 'UNIT_SPEC_OPS';
--UU
UPDATE Units SET Cost = 40, Combat= 27, RangedCombat = 0, BaseMoves = 3, BaseSightRange = 3, Range = 0
WHERE UnitType = 'UNIT_CREE_OKIHTCITAW';
UPDATE Units SET Cost = 160, Combat= 47, RangedCombat = 0, BaseMoves = 4, BaseSightRange = 4, Range = 0
WHERE UnitType = 'UNIT_INCA_WARAKAQ';
UPDATE Units SET Cost = 400, Combat= 67, RangedCombat = 0, BaseMoves = 5, BaseSightRange = 5, Range = 0
WHERE UnitType = 'UNIT_SCOTTISH_HIGHLANDER';

--v232 修复部分远程单位的克制失效
INSERT OR REPLACE INTO TypeTags
(Type,							Tag) VALUES
('UNIT_CULVERIN',				'CLASS_TRUE_RANGED'),
('UNIT_HOWITZER',				'CLASS_TRUE_RANGED'),
('UNIT_MISSILE_VEHICLE',		'CLASS_TRUE_RANGED');

--v232 平衡各个时代陆地单位上船后的战斗力
UPDATE Eras SET EmbarkedUnitStrength = 5  WHERE EraType = 'ERA_ANCIENT';--null
UPDATE Eras SET EmbarkedUnitStrength = 15 WHERE EraType = 'ERA_CLASSICAL';
UPDATE Eras SET EmbarkedUnitStrength = 25 WHERE EraType = 'ERA_MEDIEVAL';
UPDATE Eras SET EmbarkedUnitStrength = 35 WHERE EraType = 'ERA_RENAISSANCE';
UPDATE Eras SET EmbarkedUnitStrength = 45 WHERE EraType = 'ERA_INDUSTRIAL';
UPDATE Eras SET EmbarkedUnitStrength = 55 WHERE EraType = 'ERA_MODERN';
UPDATE Eras SET EmbarkedUnitStrength = 65 WHERE EraType = 'ERA_ATOMIC';
UPDATE Eras SET EmbarkedUnitStrength = 75 WHERE EraType = 'ERA_INFORMATION';
UPDATE Eras SET EmbarkedUnitStrength = 85 WHERE EraType = 'ERA_FUTURE';--null