--V224 AI yields percentage cheat
DELETE FROM TraitModifiers WHERE TraitType='TRAIT_LEADER_MAJOR_CIV' AND ModifierId='GOLDEN_AI_PRODUCTION_DIFFICULTY_SETTLER';
DELETE FROM TraitModifiers WHERE TraitType='TRAIT_LEADER_MAJOR_CIV' AND ModifierId='GOLDEN_AI_PRODUCTION_DIFFICULTY_CHIEFTAIN';
DELETE FROM TraitModifiers WHERE TraitType='TRAIT_LEADER_MAJOR_CIV' AND ModifierId='GOLDEN_AI_PRODUCTION_DIFFICULTY_WARLORD';
DELETE FROM TraitModifiers WHERE TraitType='TRAIT_LEADER_MAJOR_CIV' AND ModifierId='GOLDEN_AI_PRODUCTION_DIFFICULTY_PRINCE';
DELETE FROM TraitModifiers WHERE TraitType='TRAIT_LEADER_MAJOR_CIV' AND ModifierId='GOLDEN_AI_PRODUCTION_DIFFICULTY_KING';
DELETE FROM TraitModifiers WHERE TraitType='TRAIT_LEADER_MAJOR_CIV' AND ModifierId='GOLDEN_AI_PRODUCTION_DIFFICULTY_EMPEROR';
DELETE FROM TraitModifiers WHERE TraitType='TRAIT_LEADER_MAJOR_CIV' AND ModifierId='GOLDEN_AI_PRODUCTION_DIFFICULTY_IMMORTAL';
DELETE FROM TraitModifiers WHERE TraitType='TRAIT_LEADER_MAJOR_CIV' AND ModifierId='GOLDEN_AI_PRODUCTION_DIFFICULTY_DEITY';

--V225 War min turns
UPDATE GlobalParameters SET Value = 15 WHERE Name = 'DIPLOMACY_WAR_MIN_TURNS';