--v229 宗教压力调整
UPDATE GlobalParameters SET Value = 1 		WHERE Name = 'RELIGION_INITIAL_BELIEFS';--2
UPDATE GlobalParameters SET Value = 250 	WHERE Name = 'RELIGION_SPREAD_STRENGTH_MULTIPLIER';--200
UPDATE GlobalParameters SET Value = 30 		WHERE Name = 'RELIGION_SPREAD_ATHEISM_PRESSURE_PER_POP';--50
UPDATE GlobalParameters SET Value = 10 		WHERE Name = 'RELIGION_SPREAD_HOLY_CITY_PRESSURE_MULTIPLIER';--4
UPDATE GlobalParameters SET Value = 4 		WHERE Name = 'RELIGION_SPREAD_HOLY_SITE_PRESSURE_MULTIPLIER';--2
UPDATE GlobalParameters SET Value = 10 		WHERE Name = 'RELIGION_SPREAD_TRADE_ROUTE_PRESSURE_FOR_DESTINATION';--1
UPDATE GlobalParameters SET Value = 5 		WHERE Name = 'RELIGION_SPREAD_TRADE_ROUTE_PRESSURE_FOR_ORIGIN';--0.5