--跨时代科研与文化花费（20）
UPDATE	GlobalParameters SET Value = 66 WHERE Name = 'TECH_COST_PERCENT_CHANGE_AFTER_GAME_ERA';
UPDATE	GlobalParameters SET Value = -33 WHERE Name = 'TECH_COST_PERCENT_CHANGE_BEFORE_GAME_ERA';
UPDATE	GlobalParameters SET Value = 66 WHERE Name = 'CIVIC_COST_PERCENT_CHANGE_AFTER_GAME_ERA';
UPDATE	GlobalParameters SET Value = -33 WHERE Name = 'CIVIC_COST_PERCENT_CHANGE_BEFORE_GAME_ERA';

--尤里卡与鼓舞
UPDATE Boosts SET Boost=30;