--v234 战略资源转金币的项目
UPDATE Projects SET Cost = 100 WHERE ProjectType = 'PROJECT_HORSES_GOLD';
UPDATE Projects SET Cost = 200 WHERE ProjectType = 'PROJECT_IRON_GOLD';
UPDATE Projects SET Cost = 300 WHERE ProjectType = 'PROJECT_NITER_GOLD';
UPDATE Projects SET Cost = 400 WHERE ProjectType = 'PROJECT_COAL_GOLD';
UPDATE Projects SET Cost = 500 WHERE ProjectType = 'PROJECT_OIL_GOLD';
UPDATE Projects SET Cost = 600 WHERE ProjectType = 'PROJECT_ALUMINUM_GOLD';
UPDATE Projects SET Cost = 700 WHERE ProjectType = 'PROJECT_URANIUM_GOLD';

-- INSERT OR REPLACE INTO Projects_XP2
-- (ProjectType,							RequiredBuilding) VALUES	
-- ('PROJECT_HORSES_GOLD',		'BUILDING_MARKET'),
-- ('PROJECT_IRON_GOLD',		'BUILDING_MARKET'),
-- ('PROJECT_NITER_GOLD',		'BUILDING_BANK'),
-- ('PROJECT_COAL_GOLD',		'BUILDING_BANK'),
-- ('PROJECT_OIL_GOLD',		'BUILDING_STOCK_EXCHANGE'),
-- ('PROJECT_ALUMINUM_GOLD',	'BUILDING_STOCK_EXCHANGE'),
-- ('PROJECT_URANIUM_GOLD',	'BUILDING_STOCK_EXCHANGE');

INSERT OR REPLACE INTO Projects_XP2
(ProjectType,							RequiredBuilding) SELECT
'PROJECT_HORSES_GOLD',					'BUILDING_MINT'  WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_MINT');
INSERT OR REPLACE INTO Projects_XP2
(ProjectType,							RequiredBuilding) SELECT
'PROJECT_HORSES_GOLD',					'BUILDING_POST_STATION'  WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_POST_STATION');
INSERT OR REPLACE INTO Projects_XP2
(ProjectType,							RequiredBuilding) SELECT
'PROJECT_IRON_GOLD',					'BUILDING_MINT'  WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_MINT');
INSERT OR REPLACE INTO Projects_XP2
(ProjectType,							RequiredBuilding) SELECT
'PROJECT_IRON_GOLD',					'BUILDING_POST_STATION'  WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_POST_STATION');
INSERT OR REPLACE INTO Projects_XP2
(ProjectType,							RequiredBuilding) SELECT
'PROJECT_NITER_GOLD',					'BUILDING_COMMERCIAL'  WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_COMMERCIAL');
INSERT OR REPLACE INTO Projects_XP2
(ProjectType,							RequiredBuilding) SELECT
'PROJECT_NITER_GOLD',					'BUILDING_TAX_BUREAU'  WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_TAX_BUREAU');
INSERT OR REPLACE INTO Projects_XP2
(ProjectType,							RequiredBuilding) SELECT
'PROJECT_COAL_GOLD',					'BUILDING_COMMERCIAL'  WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_COMMERCIAL');
INSERT OR REPLACE INTO Projects_XP2
(ProjectType,							RequiredBuilding) SELECT
'PROJECT_COAL_GOLD',					'BUILDING_TAX_BUREAU'  WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_TAX_BUREAU');
INSERT OR REPLACE INTO Projects_XP2
(ProjectType,							RequiredBuilding) SELECT
'PROJECT_OIL_GOLD',						'BUILDING_URBAN_CONSTRUCTION'  WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_URBAN_CONSTRUCTION');
INSERT OR REPLACE INTO Projects_XP2
(ProjectType,							RequiredBuilding) SELECT
'PROJECT_OIL_GOLD',						'BUILDING_MILITARY_CORP'  WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_MILITARY_CORP');
INSERT OR REPLACE INTO Projects_XP2
(ProjectType,							RequiredBuilding) SELECT
'PROJECT_ALUMINUM_GOLD',				'BUILDING_URBAN_CONSTRUCTION'  WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_URBAN_CONSTRUCTION');
INSERT OR REPLACE INTO Projects_XP2
(ProjectType,							RequiredBuilding) SELECT
'PROJECT_ALUMINUM_GOLD',				'BUILDING_MILITARY_CORP'  WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_MILITARY_CORP');

DELETE FROM Projects_XP2 WHERE ProjectType='PROJECT_URANIUM_GOLD' AND EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_LUXURY_GOODS');
INSERT OR REPLACE INTO Projects_XP2
(ProjectType,							RequiredBuilding) SELECT
'PROJECT_URANIUM_GOLD',					'BUILDING_LUXURY_GOODS'  WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_LUXURY_GOODS');
INSERT OR REPLACE INTO Projects_XP2
(ProjectType,							RequiredBuilding) SELECT
'PROJECT_URANIUM_GOLD',					'BUILDING_DIGITAL_CURRENCY'  WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_DIGITAL_CURRENCY');
INSERT OR REPLACE INTO Projects_XP2
(ProjectType,							RequiredBuilding) SELECT
'PROJECT_URANIUM_GOLD',					'BUILDING_FINANCIAL_TOWER'  WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_FINANCIAL_TOWER');
INSERT OR REPLACE INTO Projects_XP2
(ProjectType,							RequiredBuilding) SELECT
'PROJECT_URANIUM_GOLD',					'BUILDING_MINING_GROUP'  WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType = 'BUILDING_MINING_GROUP');