UPDATE Civics_XP2 SET  RandomPrereqs=0, HiddenUntilPrereqComplete=0 WHERE CivicType="CIVIC_GLOBAL_WARMING_MITIGATION";
UPDATE Civics_XP2 SET  RandomPrereqs=0, HiddenUntilPrereqComplete=0 WHERE CivicType="CIVIC_SMART_POWER_DOCTRINE";
UPDATE Civics_XP2 SET  RandomPrereqs=0, HiddenUntilPrereqComplete=0 WHERE CivicType="CIVIC_INFORMATION_WARFARE";
UPDATE Civics_XP2 SET  RandomPrereqs=0, HiddenUntilPrereqComplete=0 WHERE CivicType="CIVIC_EXODUS_IMPERATIVE";
UPDATE Civics_XP2 SET  RandomPrereqs=0, HiddenUntilPrereqComplete=0 WHERE CivicType="CIVIC_CULTURAL_HEGEMONY";
UPDATE Civics_XP2 SET  RandomPrereqs=0, HiddenUntilPrereqComplete=0 WHERE CivicType="CIVIC_FUTURE_CIVIC";

--CivicPrereqs
DELETE FROM CivicPrereqs WHERE Civic='CIVIC_FUTURE_CIVIC' AND PrereqCivic='CIVIC_GLOBALIZATION';
DELETE FROM CivicPrereqs WHERE Civic='CIVIC_FUTURE_CIVIC' AND PrereqCivic='CIVIC_SOCIAL_MEDIA';


--BOOST
DELETE FROM Boosts WHERE CivicType="CIVIC_CAPITALISM";

DELETE FROM Boosts WHERE CivicType="CIVIC_HUMANISM";
DELETE FROM Boosts WHERE CivicType="CIVIC_OPERA_BALLET";
DELETE FROM Boosts WHERE CivicType="CIVIC_MASS_MEDIA";

--区域鼓舞
INSERT OR REPLACE INTO Boosts 
(CivicType , Boost, TriggerDescription , TriggerLongDescription , BoostClass , DistrictType , NumItems) VALUES
("CIVIC_CAPITALISM" , 30 , "LOC_BOOST_TRIGGER_CAPITALISM" , "LOC_BOOST_TRIGGER_LONGDESC_CAPITALISM" , "BOOST_TRIGGER_HAVE_X_DISTRICTS" , "DISTRICT_COMMERCIAL_HUB" , 5 );

--伟人鼓舞
INSERT OR REPLACE INTO Boosts   
(CivicType , 				Boost , TriggerDescription , 					TriggerLongDescription , 								BoostClass ,					Unit1Type) VALUES
("CIVIC_HUMANISM" , 		30 , 	"LOC_BOOST_TRIGGER_HUMANISM" , 			"LOC_BOOST_TRIGGER_LONGDESC_HUMANISM" , 				"BOOST_TRIGGER_TRAIN_UNIT" ,	"UNIT_GREAT_WRITER"),
("CIVIC_OPERA_BALLET" , 	30 , 	"LOC_BOOST_TRIGGER_OPERA_BALLET" , 		"LOC_BOOST_TRIGGER_LONGDESC_OPERA_BALLET" , 			"BOOST_TRIGGER_TRAIN_UNIT" , 	"UNIT_GREAT_ARTIST"),
("CIVIC_MASS_MEDIA" , 		30 , 	"LOC_BOOST_TRIGGER_MASS_MEDIA" , 		"LOC_BOOST_TRIGGER_LONGDESC_MASS_MEDIA" ,	 			"BOOST_TRIGGER_TRAIN_UNIT" , 	"UNIT_GREAT_MUSICIAN");