--------------------------------------------------------------
--Appeal change: 
--------------------------------------------------------------
UPDATE Districts	SET Appeal = -1	WHERE DistrictType = 'DISTRICT_INDUSTRIAL_ZONE';
UPDATE Districts	SET Appeal = -1	WHERE DistrictType = 'DISTRICT_ENCAMPMENT';
UPDATE Districts	SET Appeal = -1	WHERE DistrictType = 'DISTRICT_HARBOR';
--National
UPDATE Districts SET Appeal = 0 	WHERE DistrictType = 'DISTRICT_NATIONAL_CAMPUS' AND EXISTS (SELECT * FROM Districts WHERE DistrictType='DISTRICT_NATIONAL_CAMPUS');
UPDATE Districts SET Appeal = 1 	WHERE DistrictType = 'DISTRICT_NATIONAL_HOLY_SITE' AND EXISTS (SELECT * FROM Districts WHERE DistrictType='DISTRICT_NATIONAL_HOLY_SITE');
UPDATE Districts SET Appeal = 0 	WHERE DistrictType = 'DISTRICT_NATIONAL_COMMERCIAL_HUB' AND EXISTS (SELECT * FROM Districts WHERE DistrictType='DISTRICT_NATIONAL_COMMERCIAL_HUB');
UPDATE Districts SET Appeal = 1 	WHERE DistrictType = 'DISTRICT_NATIONAL_THEATER' AND EXISTS (SELECT * FROM Districts WHERE DistrictType='DISTRICT_NATIONAL_THEATER');
UPDATE Districts SET Appeal = -1 	WHERE DistrictType = 'DISTRICT_NATIONAL_INDUSTRIAL_ZONE' AND EXISTS (SELECT * FROM Districts WHERE DistrictType='DISTRICT_NATIONAL_INDUSTRIAL_ZONE');
UPDATE Districts SET Appeal = 1 	WHERE DistrictType = 'DISTRICT_NATIONAL_ENTERTAINMENT_COMPLEX' AND EXISTS (SELECT * FROM Districts WHERE DistrictType='DISTRICT_NATIONAL_ENTERTAINMENT_COMPLEX');
UPDATE Districts SET Appeal = -1 	WHERE DistrictType = 'DISTRICT_NATIONAL_ENCAMPMENT' AND EXISTS (SELECT * FROM Districts WHERE DistrictType='DISTRICT_NATIONAL_ENCAMPMENT');
UPDATE Districts SET Appeal = -1 	WHERE DistrictType = 'DISTRICT_NATIONAL_HARBOR' AND EXISTS (SELECT * FROM Districts WHERE DistrictType='DISTRICT_NATIONAL_HARBOR');

--工业区T3建筑
INSERT OR REPLACE INTO BuildingModifiers (BuildingType, ModifierId) VALUES 
('BUILDING_COAL_POWER_PLANT', 			'GOLDEN_IZ_T3_APPEAL_DEBUFF'),
('BUILDING_FOSSIL_FUEL_POWER_PLANT', 	'GOLDEN_IZ_T3_APPEAL_DEBUFF');
-- ('BUILDING_POWER_PLANT', 				'GOLDEN_IZ_T3_APPEAL_DEBUFF');
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId) VALUES 
('GOLDEN_IZ_T3_APPEAL_DEBUFF', 'MODIFIER_SINGLE_CITY_ADJUST_CITY_APPEAL', NULL);
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value) VALUES 
('GOLDEN_IZ_T3_APPEAL_DEBUFF', 'Amount', -1);