--V224 政体专属政策不再只能放通配符
UPDATE Policies SET GovernmentSlotType="SLOT_MILITARY" WHERE PolicyType="POLICY_COLLECTIVE_PRODUCTION";
UPDATE Policies SET GovernmentSlotType="SLOT_MILITARY" WHERE PolicyType="POLICY_THIRD_ALTERNATIVE";
UPDATE Policies SET GovernmentSlotType="SLOT_MILITARY" WHERE PolicyType="POLICY_WARS_OF_RELIGION";
UPDATE Policies SET GovernmentSlotType="SLOT_MILITARY" WHERE PolicyType="POLICY_MARTIAL_LAW";

UPDATE Policies SET GovernmentSlotType="SLOT_ECONOMIC" WHERE PolicyType="POLICY_RESEARCH_FUNDING";
UPDATE Policies SET GovernmentSlotType="SLOT_ECONOMIC" WHERE PolicyType="POLICY_BIG_EXPANSION";
UPDATE Policies SET GovernmentSlotType="SLOT_ECONOMIC" WHERE PolicyType="POLICY_PROSPEROUS_PORT";
UPDATE Policies SET GovernmentSlotType="SLOT_ECONOMIC" WHERE PolicyType="POLICY_CHURCH_COMMUNITY";
UPDATE Policies SET GovernmentSlotType="SLOT_ECONOMIC" WHERE PolicyType="POLICY_NEW_DEAL";
UPDATE Policies SET GovernmentSlotType="SLOT_ECONOMIC" WHERE PolicyType="POLICY_MEDINA_QUARTER";

UPDATE Policies SET GovernmentSlotType="SLOT_DIPLOMATIC" WHERE PolicyType="POLICY_COLLECTIVIZATION";
UPDATE Policies SET GovernmentSlotType="SLOT_DIPLOMATIC" WHERE PolicyType="POLICY_CIVIL_PRESTIGE";