-- Icons
-- DateCreated: 9/12/2021 9:56:14 AM
--------------------------------------------------------------
-- IconTextureAtlases
INSERT OR REPLACE INTO IconTextureAtlases 
(Name,									IconSize,	IconsPerRow,	IconsPerColumn,	Filename)
VALUES
-- Unit Flags
('ICON_ATLAS_GA_NAVAL_UNITS',			22,			5,				4,				'GA_UnitIcons_Naval_22'),
('ICON_ATLAS_GA_NAVAL_UNITS',			32,			5,				4,				'GA_UnitIcons_Naval_32'),
('ICON_ATLAS_GA_NAVAL_UNITS',			38,			5,				4,				'GA_UnitIcons_Naval_38'),
('ICON_ATLAS_GA_NAVAL_UNITS',			50,			5,				4,				'GA_UnitIcons_Naval_50'),
('ICON_ATLAS_GA_NAVAL_UNITS',			80,			5,				4,				'GA_UnitIcons_Naval_80'),
('ICON_ATLAS_GA_NAVAL_UNITS',			256,		5,				4,				'GA_UnitIcons_Naval_256');

INSERT OR REPLACE INTO IconTextureAtlases 
(Name,											IconSize,	IconsPerRow,	IconsPerColumn, Filename)
VALUES
('ICON_ATLAS_GA_UNITS_FIRESUPPORT',				22,			3,				2,				'ICON_GA_SHORTRANGE_UNITS_22'),
('ICON_ATLAS_GA_UNITS_FIRESUPPORT',				32,			3,				2,				'ICON_GA_SHORTRANGE_UNITS_32'),
('ICON_ATLAS_GA_UNITS_FIRESUPPORT',				38,			3,				2,				'ICON_GA_SHORTRANGE_UNITS_38'),
('ICON_ATLAS_GA_UNITS_FIRESUPPORT',				50,			3,				2,				'ICON_GA_SHORTRANGE_UNITS_50'),
('ICON_ATLAS_GA_UNITS_FIRESUPPORT',				80,			3,				2,				'ICON_GA_SHORTRANGE_UNITS_80'),
('ICON_ATLAS_GA_UNITS_FIRESUPPORT',				256,		3,				2,				'ICON_GA_SHORTRANGE_UNITS_256');
-- IconDefinitions
INSERT OR REPLACE INTO IconDefinitions 
(Name,									Atlas,									'Index')
VALUES
('ICON_UNIT_LEMBOS',					'ICON_ATLAS_GA_NAVAL_UNITS',			5),
('ICON_UNIT_LEMBOS_WHITE',				'ICON_ATLAS_GA_NAVAL_UNITS',			5),
('ICON_UNIT_LEMBOS_BLACK',				'ICON_ATLAS_GA_NAVAL_UNITS',			5),
('ICON_UNIT_COG',						'ICON_ATLAS_GA_NAVAL_UNITS',			6),
('ICON_UNIT_COG_WHITE',					'ICON_ATLAS_GA_NAVAL_UNITS',			6),
('ICON_UNIT_COG_BLACK',					'ICON_ATLAS_GA_NAVAL_UNITS',			6),
('ICON_UNIT_TORPEDO_GUNBOAT',			'ICON_ATLAS_GA_NAVAL_UNITS',			7),
('ICON_UNIT_TORPEDO_GUNBOAT_WHITE',		'ICON_ATLAS_GA_NAVAL_UNITS',			7),
('ICON_UNIT_TORPEDO_GUNBOAT_BLACK',		'ICON_ATLAS_GA_NAVAL_UNITS',			7),
('ICON_UNIT_MISSILE_FRIGATE',			'ICON_ATLAS_GA_NAVAL_UNITS',			8),
('ICON_UNIT_MISSILE_FRIGATE_WHITE',		'ICON_ATLAS_GA_NAVAL_UNITS',			8),
('ICON_UNIT_MISSILE_FRIGATE_BLACK',		'ICON_ATLAS_GA_NAVAL_UNITS',			8),
('ICON_UNIT_GALLEASS',					'ICON_ATLAS_GA_NAVAL_UNITS',			10),
('ICON_UNIT_GALLEASS_WHITE',			'ICON_ATLAS_GA_NAVAL_UNITS',			10),
('ICON_UNIT_GALLEASS_BLACK',			'ICON_ATLAS_GA_NAVAL_UNITS',			10),
('ICON_UNIT_ARMORED_CRUISER',			'ICON_ATLAS_GA_NAVAL_UNITS',			11),
('ICON_UNIT_ARMORED_CRUISER_WHITE',		'ICON_ATLAS_GA_NAVAL_UNITS',			11),
('ICON_UNIT_ARMORED_CRUISER_BLACK',		'ICON_ATLAS_GA_NAVAL_UNITS',			11),
('ICON_UNIT_BATTLECRUISER',				'ICON_ATLAS_GA_NAVAL_UNITS',			12),
('ICON_UNIT_BATTLECRUISER_WHITE',		'ICON_ATLAS_GA_NAVAL_UNITS',			12),
('ICON_UNIT_BATTLECRUISER_BLACK',		'ICON_ATLAS_GA_NAVAL_UNITS',			12);

INSERT OR REPLACE INTO IconDefinitions 
(Name,											Atlas,										'Index')
VALUES
('ICON_UNIT_FIRESUPPORT1',						'ICON_ATLAS_UNITS',							23),
('ICON_UNIT_FIRESUPPORT2',						'ICON_ATLAS_GA_UNITS_FIRESUPPORT',			0),
('ICON_UNIT_FIRESUPPORT3',						'ICON_ATLAS_GA_UNITS_FIRESUPPORT',			1),
('ICON_UNIT_FIRESUPPORT4',						'ICON_ATLAS_GA_UNITS_FIRESUPPORT',			2),
('ICON_UNIT_FIRESUPPORT5',						'ICON_ATLAS_GA_UNITS_FIRESUPPORT',			3),
('ICON_UNIT_FIRESUPPORT6',						'ICON_ATLAS_GA_UNITS_FIRESUPPORT',			4),
('ICON_UNIT_FIRESUPPORT7',						'ICON_ATLAS_GA_UNITS_FIRESUPPORT',			5),
('ICON_UNIT_FIRESUPPORT8',						'ICON_ATLAS_GA_UNITS_FIRESUPPORT',			6),

('ICON_UNIT_FIRESUPPORT1_PORTRAIT',				'ICON_ATLAS_UNIT_PORTRAITS',		34),
('ICON_UNIT_FIRESUPPORT2_PORTRAIT',				'ICON_ATLAS_UNIT_PORTRAITS',		34),
('ICON_UNIT_FIRESUPPORT3_PORTRAIT',				'ICON_ATLAS_UNIT_PORTRAITS',		34),
('ICON_UNIT_FIRESUPPORT4_PORTRAIT',				'ICON_ATLAS_UNIT_PORTRAITS',		34),
('ICON_UNIT_FIRESUPPORT5_PORTRAIT',				'ICON_ATLAS_UNIT_PORTRAITS',		60),
('ICON_UNIT_FIRESUPPORT6_PORTRAIT',				'ICON_ATLAS_UNIT_PORTRAITS',		60),
('ICON_UNIT_FIRESUPPORT7_PORTRAIT',				'ICON_ATLAS_UNIT_PORTRAITS_2',		29),
('ICON_UNIT_FIRESUPPORT8_PORTRAIT',				'ICON_ATLAS_UNIT_PORTRAITS_2',		29);