--CSE
DELETE FROM TraitModifiers WHERE TraitType LIKE 'MINOR_CIV_%' AND ModifierId LIKE 'MODIFIER_CSE_CULTURAL%';
DELETE FROM TraitModifiers WHERE TraitType LIKE 'MINOR_CIV_%' AND ModifierId LIKE 'MODIFIER_CSE_INDUSTRIAL%';
DELETE FROM TraitModifiers WHERE TraitType LIKE 'MINOR_CIV_%' AND ModifierId LIKE 'MODIFIER_CSE_MILITARISTIC%';
DELETE FROM TraitModifiers WHERE TraitType LIKE 'MINOR_CIV_%' AND ModifierId LIKE 'MODIFIER_CSE_RELIGIOUS%';
DELETE FROM TraitModifiers WHERE TraitType LIKE 'MINOR_CIV_%' AND ModifierId LIKE 'MODIFIER_CSE_SCIENTIFIC%';
DELETE FROM TraitModifiers WHERE TraitType LIKE 'MINOR_CIV_%' AND ModifierId LIKE 'MODIFIER_CSE_TRADE%';
DELETE FROM TraitModifiers WHERE TraitType LIKE 'MINOR_CIV_%' AND ModifierId LIKE 'MODIFIER_CSE_MARITIME%';

DELETE FROM TraitModifiers WHERE TraitType = 'MINOR_CIV_TRADE_TRAIT' AND ModifierId = 'GA_MINOR_CIV_TRADE_SMALL_NONSUZERAIN_DISTRICT_HARBOR_YIELD_GOLD';
DELETE FROM TraitModifiers WHERE TraitType = 'MINOR_CIV_TRADE_TRAIT' AND ModifierId = 'GA_MINOR_CIV_TRADE_SMALL_SUZERAIN_DISTRICT_HARBOR_YIELD_GOLD';
DELETE FROM TraitModifiers WHERE TraitType = 'MINOR_CIV_TRADE_TRAIT' AND ModifierId = 'GA_MINOR_CIV_TRADE_MEDIUM_NONSUZERAIN_BUILDING_LIGHTHOUSE_YIELD_GOLD';
DELETE FROM TraitModifiers WHERE TraitType = 'MINOR_CIV_TRADE_TRAIT' AND ModifierId = 'GA_MINOR_CIV_TRADE_MEDIUM_SUZERAIN_BUILDING_LIGHTHOUSE_YIELD_GOLD';
DELETE FROM TraitModifiers WHERE TraitType = 'MINOR_CIV_TRADE_TRAIT' AND ModifierId = 'GA_MINOR_CIV_TRADE_LARGE_NONSUZERAIN_BUILDING_SHIPYARD_YIELD_GOLD';
DELETE FROM TraitModifiers WHERE TraitType = 'MINOR_CIV_TRADE_TRAIT' AND ModifierId = 'GA_MINOR_CIV_TRADE_LARGE_SUZERAIN_BUILDING_SHIPYARD_YIELD_GOLD';
DELETE FROM TraitModifiers WHERE TraitType = 'MINOR_CIV_TRADE_TRAIT' AND ModifierId = 'GA_MINOR_CIV_TRADE_LARGEST_NONSUZERAIN_BUILDING_SEAPORT_YIELD_GOLD';
DELETE FROM TraitModifiers WHERE TraitType = 'MINOR_CIV_TRADE_TRAIT' AND ModifierId = 'GA_MINOR_CIV_TRADE_LARGEST_SUZERAIN_BUILDING_SEAPORT_YIELD_GOLD';


INSERT INTO TraitModifiers 
(TraitType, 									ModifierId) VALUES
('MINOR_CIV_CSE_MARITIME_TRAIT' ,				'GA_MINOR_CIV_TRADE_SMALL_NONSUZERAIN_DISTRICT_HARBOR_YIELD_GOLD'),
('MINOR_CIV_CSE_MARITIME_TRAIT' ,				'GA_MINOR_CIV_TRADE_SMALL_SUZERAIN_DISTRICT_HARBOR_YIELD_GOLD'),
('MINOR_CIV_CSE_MARITIME_TRAIT' ,				'GA_MINOR_CIV_TRADE_MEDIUM_NONSUZERAIN_BUILDING_LIGHTHOUSE_YIELD_GOLD'),
('MINOR_CIV_CSE_MARITIME_TRAIT' ,				'GA_MINOR_CIV_TRADE_MEDIUM_SUZERAIN_BUILDING_LIGHTHOUSE_YIELD_GOLD'),
('MINOR_CIV_CSE_MARITIME_TRAIT' ,				'GA_MINOR_CIV_TRADE_LARGE_NONSUZERAIN_BUILDING_SHIPYARD_YIELD_GOLD'),
('MINOR_CIV_CSE_MARITIME_TRAIT' ,				'GA_MINOR_CIV_TRADE_LARGE_SUZERAIN_BUILDING_SHIPYARD_YIELD_GOLD'),
('MINOR_CIV_CSE_MARITIME_TRAIT' ,				'GA_MINOR_CIV_TRADE_LARGEST_NONSUZERAIN_BUILDING_SEAPORT_YIELD_GOLD'),
('MINOR_CIV_CSE_MARITIME_TRAIT' ,				'GA_MINOR_CIV_TRADE_LARGEST_SUZERAIN_BUILDING_SEAPORT_YIELD_GOLD');
