------
--LA--
------
--TraitModifiers
DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_LEADER_GEDEMO_BISMARK';
INSERT OR REPLACE INTO TraitModifiers (TraitType, 			ModifierId) VALUES	
('TRAIT_LEADER_GEDEMO_BISMARK',	'GA_TRAIT_BISMARK_FRIENDLY_TERRITORY_COMBAT'),
('TRAIT_LEADER_GEDEMO_BISMARK',	'GA_TRAIT_BISMARK_MELEE_FROM_UD'),
('TRAIT_LEADER_GEDEMO_BISMARK',	'GA_TRAIT_BISMARK_FREE_POWER');
----Modifiers
INSERT OR REPLACE INTO Modifiers (ModifierId,						ModifierType,												SubjectRequirementSetId) VALUES
('GA_TRAIT_BISMARK_FRIENDLY_TERRITORY_COMBAT',						'MODIFIER_PLAYER_UNITS_GRANT_ABILITY',	        			NULL),
('GA_TRAIT_BISMARK_MELEE_FROM_UD',									'MODIFIER_PLAYER_CITIES_GRANT_UNIT_BY_CLASS',	        	'GOLDEN_CITY_HAS_DISTRICT_HANSA_REQUIREMENTS'),
('GA_TRAIT_BISMARK_FREE_POWER',										'MODIFIER_PLAYER_CITIES_ADJUST_FREE_POWER',	        		'GOLDEN_PLAYER_HAS_TECH_ELECTRICITY_REQUIREMENTS');
--ModifierArguments
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,						Value) VALUES
('GA_TRAIT_BISMARK_FRIENDLY_TERRITORY_COMBAT',					'AbilityType',       		'ABILITY_BISMARK_FRIENDLY_TERRITORY_COMBAT'),
('GA_TRAIT_BISMARK_MELEE_FROM_UD',								'UnitPromotionClassType',   'PROMOTION_CLASS_MELEE'),
('GA_TRAIT_BISMARK_FREE_POWER',									'SourceType',    			'FREE_POWER_SOURCE_WATER'),
('GA_TRAIT_BISMARK_FREE_POWER',									'Amount',       			10);
-- Types
INSERT OR REPLACE INTO Types (Type,						Kind) VALUES
('ABILITY_BISMARK_FRIENDLY_TERRITORY_COMBAT',					'KIND_ABILITY');
-- TypeTags
INSERT OR REPLACE INTO TypeTags (Type,									Tag) VALUES	
('ABILITY_BISMARK_FRIENDLY_TERRITORY_COMBAT',				'CLASS_LIGHT_CAVALRY'),
('ABILITY_BISMARK_FRIENDLY_TERRITORY_COMBAT',			    'CLASS_HEAVY_CAVALRY'),
('ABILITY_BISMARK_FRIENDLY_TERRITORY_COMBAT',			    'CLASS_MELEE'),
('ABILITY_BISMARK_FRIENDLY_TERRITORY_COMBAT',			    'CLASS_TRUE_RANGED'),
('ABILITY_BISMARK_FRIENDLY_TERRITORY_COMBAT',			    'CLASS_SIEGE'),
('ABILITY_BISMARK_FRIENDLY_TERRITORY_COMBAT',			    'CLASS_RECON'),
('ABILITY_BISMARK_FRIENDLY_TERRITORY_COMBAT',			    'CLASS_ANTI_CAVALRY');
-- UnitAbilities
INSERT OR REPLACE INTO UnitAbilities (UnitAbilityType,		Name,													Description, 													Inactive) VALUES	
('ABILITY_BISMARK_FRIENDLY_TERRITORY_COMBAT',				'LOC_ABILITY_BISMARK_FRIENDLY_TERRITORY_COMBAT_NAME',	'LOC_ABILITY_BISMARK_FRIENDLY_TERRITORY_COMBAT_DESCRIPTION', 	1);
-- UnitAbilityModifiers
INSERT OR REPLACE INTO UnitAbilityModifiers (UnitAbilityType,						ModifierId) VALUES	
('ABILITY_BISMARK_FRIENDLY_TERRITORY_COMBAT',			            'BISMARK_FRIENDLY_TERRITORY_COMBAT');
----Modifiers
INSERT OR REPLACE INTO Modifiers (ModifierId,						ModifierType,												SubjectRequirementSetId) VALUES
('BISMARK_FRIENDLY_TERRITORY_COMBAT',								'MODIFIER_UNIT_ADJUST_COMBAT_STRENGTH',	        			'COSSACK_PLOT_IS_OWNER_OR_ADJACENT_REQUIREMENTS');
--ModifierArguments
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,						Value) VALUES
('BISMARK_FRIENDLY_TERRITORY_COMBAT',							'Amount',       			10);
--ModifierStrings
INSERT OR REPLACE INTO ModifierStrings (ModifierId,			Context,						Text) VALUES
('BISMARK_FRIENDLY_TERRITORY_COMBAT',						'Preview',       				'LOC_BISMARK_FRIENDLY_TERRITORY_COMBAT');