--NETHERLANDS 荷兰 LEADER_WILLIAM_OF_ORANGE
INSERT OR REPLACE INTO PlayerItems (CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('CIVILIZATION_NETHERLANDS', 'LEADER_WILLIAM_OF_ORANGE', 'GOLDEN_CIVILIZATION_NETHERLANDS_CUSTOM_FEATURES', 'ICON_CIVILIZATION_NETHERLANDS', 'LOC_GOLDEN_CIVILIZATION_NETHERLANDS_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_NETHERLANDS_CUSTOM_FEATURES_DESCRIPTION', 40),
('CIVILIZATION_NETHERLANDS', 'LEADER_WILLIAM_OF_ORANGE', 'GOLDEN_TRAIT_CIVILIZATION_NETHERLANDS', 'ICON_CIVILIZATION_NETHERLANDS', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_NETHERLANDS_DESCRIPTION', 50);

INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion1_Players', 'CIVILIZATION_NETHERLANDS', 'LEADER_WILLIAM_OF_ORANGE', 'GOLDEN_CIVILIZATION_NETHERLANDS_CUSTOM_FEATURES', 'ICON_CIVILIZATION_NETHERLANDS', 'LOC_GOLDEN_CIVILIZATION_NETHERLANDS_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_NETHERLANDS_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion1_Players', 'CIVILIZATION_NETHERLANDS', 'LEADER_WILLIAM_OF_ORANGE', 'GOLDEN_TRAIT_CIVILIZATION_NETHERLANDS', 'ICON_CIVILIZATION_NETHERLANDS', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_NETHERLANDS_DESCRIPTION', 50);

INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_NETHERLANDS', 'LEADER_WILLIAM_OF_ORANGE', 'GOLDEN_CIVILIZATION_NETHERLANDS_CUSTOM_FEATURES', 'ICON_CIVILIZATION_NETHERLANDS', 'LOC_GOLDEN_CIVILIZATION_NETHERLANDS_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_NETHERLANDS_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_NETHERLANDS', 'LEADER_WILLIAM_OF_ORANGE', 'GOLDEN_TRAIT_CIVILIZATION_NETHERLANDS', 'ICON_CIVILIZATION_NETHERLANDS', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_NETHERLANDS_DESCRIPTION', 50);

--GERMANY 德国 LEADER_GEDEMO_BISMARK
INSERT OR REPLACE INTO PlayerItems (CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('CIVILIZATION_GERMANY', 'LEADER_GEDEMO_BISMARK', 'GOLDEN_CIVILIZATION_GERMANY_CUSTOM_FEATURES', 'ICON_CIVILIZATION_GERMANY', 'LOC_GOLDEN_CIVILIZATION_GERMANY_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_GERMANY_CUSTOM_FEATURES_DESCRIPTION', 40),
('CIVILIZATION_GERMANY', 'LEADER_GEDEMO_BISMARK', 'GOLDEN_TRAIT_CIVILIZATION_GERMANY', 'ICON_CIVILIZATION_GERMANY', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_GERMANY_DESCRIPTION', 50);

INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion1_Players', 'CIVILIZATION_GERMANY', 'LEADER_GEDEMO_BISMARK', 'GOLDEN_CIVILIZATION_GERMANY_CUSTOM_FEATURES', 'ICON_CIVILIZATION_GERMANY', 'LOC_GOLDEN_CIVILIZATION_GERMANY_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_GERMANY_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion1_Players', 'CIVILIZATION_GERMANY', 'LEADER_GEDEMO_BISMARK', 'GOLDEN_TRAIT_CIVILIZATION_GERMANY', 'ICON_CIVILIZATION_GERMANY', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_GERMANY_DESCRIPTION', 50);

INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_GERMANY', 'LEADER_GEDEMO_BISMARK', 'GOLDEN_CIVILIZATION_GERMANY_CUSTOM_FEATURES', 'ICON_CIVILIZATION_GERMANY', 'LOC_GOLDEN_CIVILIZATION_GERMANY_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_GERMANY_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_GERMANY', 'LEADER_GEDEMO_BISMARK', 'GOLDEN_TRAIT_CIVILIZATION_GERMANY', 'ICON_CIVILIZATION_GERMANY', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_GERMANY_DESCRIPTION', 50);

--PERSIA 波斯 LEADER_CVS_DARIUS
INSERT OR REPLACE INTO PlayerItems (CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('CIVILIZATION_PERSIA', 'LEADER_CVS_DARIUS', 'GOLDEN_CIVILIZATION_PERSIA_CUSTOM_FEATURES', 'ICON_CIVILIZATION_PERSIA', 'LOC_GOLDEN_CIVILIZATION_PERSIA_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_PERSIA_CUSTOM_FEATURES_DESCRIPTION', 40),
('CIVILIZATION_PERSIA', 'LEADER_CVS_DARIUS', 'GOLDEN_TRAIT_CIVILIZATION_PERSIA', 'ICON_CIVILIZATION_PERSIA', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_PERSIA_DESCRIPTION', 50);

INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion1_Players', 'CIVILIZATION_PERSIA', 'LEADER_CVS_DARIUS', 'GOLDEN_CIVILIZATION_PERSIA_CUSTOM_FEATURES', 'ICON_CIVILIZATION_PERSIA', 'LOC_GOLDEN_CIVILIZATION_PERSIA_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_PERSIA_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion1_Players', 'CIVILIZATION_PERSIA', 'LEADER_CVS_DARIUS', 'GOLDEN_TRAIT_CIVILIZATION_PERSIA', 'ICON_CIVILIZATION_PERSIA', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_PERSIA_DESCRIPTION', 50);

INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_PERSIA', 'LEADER_CVS_DARIUS', 'GOLDEN_CIVILIZATION_PERSIA_CUSTOM_FEATURES', 'ICON_CIVILIZATION_PERSIA', 'LOC_GOLDEN_CIVILIZATION_PERSIA_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_PERSIA_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_PERSIA', 'LEADER_CVS_DARIUS', 'GOLDEN_TRAIT_CIVILIZATION_PERSIA', 'ICON_CIVILIZATION_PERSIA', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_PERSIA_DESCRIPTION', 50);

--INDONESIA 印度尼西亚 LEADER_CVS_GAJAH_MADA
INSERT OR REPLACE INTO PlayerItems (CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('CIVILIZATION_INDONESIA', 'LEADER_CVS_GAJAH_MADA', 'GOLDEN_CIVILIZATION_INDONESIA_CUSTOM_FEATURES', 'ICON_CIVILIZATION_INDONESIA', 'LOC_GOLDEN_CIVILIZATION_INDONESIA_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_INDONESIA_CUSTOM_FEATURES_DESCRIPTION', 40),
('CIVILIZATION_INDONESIA', 'LEADER_CVS_GAJAH_MADA', 'GOLDEN_TRAIT_CIVILIZATION_INDONESIA', 'ICON_CIVILIZATION_INDONESIA', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_INDONESIA_DESCRIPTION', 50);

INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion1_Players', 'CIVILIZATION_INDONESIA', 'LEADER_CVS_GAJAH_MADA', 'GOLDEN_CIVILIZATION_INDONESIA_CUSTOM_FEATURES', 'ICON_CIVILIZATION_INDONESIA', 'LOC_GOLDEN_CIVILIZATION_INDONESIA_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_INDONESIA_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion1_Players', 'CIVILIZATION_INDONESIA', 'LEADER_CVS_GAJAH_MADA', 'GOLDEN_TRAIT_CIVILIZATION_INDONESIA', 'ICON_CIVILIZATION_INDONESIA', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_INDONESIA_DESCRIPTION', 50);

INSERT OR REPLACE INTO PlayerItems (Domain, CivilizationType, LeaderType, Type, Icon, Name, Description, SortIndex) VALUES
('Players:Expansion2_Players', 'CIVILIZATION_INDONESIA', 'LEADER_CVS_GAJAH_MADA', 'GOLDEN_CIVILIZATION_INDONESIA_CUSTOM_FEATURES', 'ICON_CIVILIZATION_INDONESIA', 'LOC_GOLDEN_CIVILIZATION_INDONESIA_CUSTOM_FEATURES_NAME', 'LOC_GOLDEN_CIVILIZATION_INDONESIA_CUSTOM_FEATURES_DESCRIPTION', 40),
('Players:Expansion2_Players', 'CIVILIZATION_INDONESIA', 'LEADER_CVS_GAJAH_MADA', 'GOLDEN_TRAIT_CIVILIZATION_INDONESIA', 'ICON_CIVILIZATION_INDONESIA', 'LOC_GOLDEN_TRAIT_NAME', 'LOC_GOLDEN_TRAIT_CIVILIZATION_INDONESIA_DESCRIPTION', 50);
