
--DistrictModifiers
DELETE FROM DistrictModifiers WHERE DistrictType = 'DISTRICT_CITY_CENTER' AND ModifierId = 'CVS_GAJA_MADA_UA_PALACE_FOOD';
DELETE FROM DistrictModifiers WHERE DistrictType = 'DISTRICT_CITY_CENTER' AND ModifierId = 'CVS_GAJA_MADA_UA_PALACE_PROD';

--TraitModifiers
INSERT OR REPLACE INTO TraitModifiers (TraitType, 			ModifierId) VALUES	
('TRAIT_LEADER_CVS_GAJAH_MADA_UA',	'TRAIT_IGNORE_EMBARK_DISEMBARK_COST_RELIGIOUS'),--Base game
('TRAIT_LEADER_CVS_GAJAH_MADA_UA',	'GA_TRAIT_GAJAH_MADA_TRADE_ROUTE_CAPACITY'),
('TRAIT_LEADER_CVS_GAJAH_MADA_UA',	'GA_TRAIT_GAJAH_MADA_TRADER');

----Modifiers
INSERT OR REPLACE INTO Modifiers (ModifierId, 				ModifierType, 												SubjectRequirementSetId) VALUES
('GA_TRAIT_GAJAH_MADA_TRADE_ROUTE_CAPACITY',				'MODIFIER_PLAYER_CITIES_ADJUST_TRADE_ROUTE_CAPACITY',		'GOLDEN_PLOT_ADJACENT_TO_COAST_REQUIREMENTS'),
('GA_TRAIT_GAJAH_MADA_TRADER',								'GOLDEN_MODIFIER_PLAYER_CITIES_GRANT_UNIT',					'GOLDEN_PLOT_ADJACENT_TO_COAST_REQUIREMENTS');

--ModifierArguments
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		    Value) VALUES
('GA_TRAIT_GAJAH_MADA_TRADE_ROUTE_CAPACITY',					'Amount',		1),
('GA_TRAIT_GAJAH_MADA_TRADER',									'UnitType',		'UNIT_TRADER'),
('GA_TRAIT_GAJAH_MADA_TRADER',									'Amount',		1);

UPDATE ModifierArguments SET  Value = 10
WHERE ModifierId = 'ABILITY_CVS_GAJA_MADAH_UA_MOD' AND Name = 'Amount';

--RequirementSetRequirements
UPDATE RequirementSetRequirements SET  RequirementId = 'REQUIRES_UNIT_ON_COASTAL_LAND'
WHERE RequirementSetId = 'CVS_GAJAH_MADA_ABILITY_REQUIREMENTS' AND RequirementId = 'REQUIRES_UNIT_ON_HOME_CONTINENT';

--TypeTags ABILITY_GITARJA_RELIGIOUS_NO_EMBARK_DISEMBARK_COST
INSERT OR REPLACE INTO TypeTags (Type,									Tag) VALUES	
('ABILITY_GITARJA_RELIGIOUS_NO_EMBARK_DISEMBARK_COST',				'CLASS_LANDCIVILIAN'),
('ABILITY_GITARJA_RELIGIOUS_NO_EMBARK_DISEMBARK_COST',				'CLASS_LIGHT_CAVALRY'),
('ABILITY_GITARJA_RELIGIOUS_NO_EMBARK_DISEMBARK_COST',			    'CLASS_HEAVY_CAVALRY'),
('ABILITY_GITARJA_RELIGIOUS_NO_EMBARK_DISEMBARK_COST',			    'CLASS_MELEE'),
('ABILITY_GITARJA_RELIGIOUS_NO_EMBARK_DISEMBARK_COST',			    'CLASS_TRUE_RANGED'),
('ABILITY_GITARJA_RELIGIOUS_NO_EMBARK_DISEMBARK_COST',			    'CLASS_SIEGE'),
('ABILITY_GITARJA_RELIGIOUS_NO_EMBARK_DISEMBARK_COST',			    'CLASS_RECON'),
('ABILITY_GITARJA_RELIGIOUS_NO_EMBARK_DISEMBARK_COST',			    'CLASS_ANTI_CAVALRY');

--UU
UPDATE Units SET Cost = 220, Combat= 30, RangedCombat = 45, PrereqTech = 'TECH_APPRENTICESHIP'
WHERE UnitType = 'UNIT_CVS_GAJAH_MADA_UU';