--V229 削弱自由探索系列
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_CULTURE_INDUSTRY' AND ModifierId='GOLDEN_CULTURE_INDUSTRY_THEATER_GOLD';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_HEARTBEAT_OF_STEAM' AND ModifierId='GOLDEN_HEARTBEAT_OF_STEAM_INDUSTRIAL_GOLD';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_FREE_ENQUIRY' AND ModifierId='POLICY_FREE_ENQUIRY_GA_CAMPUS';
INSERT OR REPLACE INTO PolicyModifiers 
(PolicyType,                           		ModifierId)VALUES	
('POLICY_MANDALA_STATE',          			'GOLDEN_CULTURE_INDUSTRY_THEATER_GOLD'),
('POLICY_MILITARY_INDUSTRIAL_COMPLEX',      'GOLDEN_HEARTBEAT_OF_STEAM_INDUSTRIAL_GOLD'),
('POLICY_SKY_AND_STARS',      				'POLICY_FREE_ENQUIRY_GA_CAMPUS');