--V229 改回原版
--格鲁吉亚
DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS_NEW' AND EXISTS (SELECT * FROM TraitModifiers WHERE TraitType='TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS_NEW');
INSERT OR REPLACE INTO TraitModifiers (TraitType, 			ModifierId) VALUES	
('TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS_NEW',	'TRAIT_WALLS_PRODUCTION'),--Base game
('TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS_NEW',	'TRAIT_CASTLE_PRODUCTION'),--Base game
('TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS_NEW',	'TRAIT_TSIKHE_PRODUCTION'),--Base game
('TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS_NEW',	'TRAIT_STAR_FORT_PRODUCTION'),--Base game
('TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS_NEW',	'TRAIT_GOLDEN_AGE_WILDCARD_SLOT'),--Base game
('TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS_NEW',	'TRAIT_GOLDEN_AGE_UNLOCK_DARK_POLICIES');--Base game
UPDATE Traits SET Description = 'LOC_TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS_DESCRIPTION'
WHERE Description = 'LOC_TRAIT_CIVILIZATION_GOLDEN_AGE_QUESTS_MODE_DESCRIPTION';

--自由城市忠诚度压力
UPDATE TypeProperties SET Value = 1
WHERE Name = 'FREE_CITY_INFLUENCE' AND Type = "DIFFICULTY_SETTLER";
UPDATE TypeProperties SET Value = 2
WHERE Name = 'FREE_CITY_INFLUENCE' AND Type = "DIFFICULTY_CHIEFTAIN";
UPDATE TypeProperties SET Value = 2.5
WHERE Name = 'FREE_CITY_INFLUENCE' AND Type = "DIFFICULTY_WARLORD";
UPDATE TypeProperties SET Value = 3
WHERE Name = 'FREE_CITY_INFLUENCE' AND Type = "DIFFICULTY_PRINCE";
UPDATE TypeProperties SET Value = 3.5
WHERE Name = 'FREE_CITY_INFLUENCE' AND Type = "DIFFICULTY_KING";
UPDATE TypeProperties SET Value = 4
WHERE Name = 'FREE_CITY_INFLUENCE' AND Type = "DIFFICULTY_EMPEROR";
UPDATE TypeProperties SET Value = 4.5
WHERE Name = 'FREE_CITY_INFLUENCE' AND Type = "DIFFICULTY_IMMORTAL";
UPDATE TypeProperties SET Value = 5
WHERE Name = 'FREE_CITY_INFLUENCE' AND Type = "DIFFICULTY_DEITY";

--自由城市比例
UPDATE TypeProperties SET Value = 5
WHERE Name = 'DARK_AGE_CITIES_LOST_PLAYER' AND Type = "DIFFICULTY_SETTLER";
UPDATE TypeProperties SET Value = 10
WHERE Name = 'DARK_AGE_CITIES_LOST_PLAYER' AND Type = "DIFFICULTY_CHIEFTAIN";
UPDATE TypeProperties SET Value = 15
WHERE Name = 'DARK_AGE_CITIES_LOST_PLAYER' AND Type = "DIFFICULTY_WARLORD";
UPDATE TypeProperties SET Value = 20
WHERE Name = 'DARK_AGE_CITIES_LOST_PLAYER' AND Type = "DIFFICULTY_PRINCE";
UPDATE TypeProperties SET Value = 25
WHERE Name = 'DARK_AGE_CITIES_LOST_PLAYER' AND Type = "DIFFICULTY_KING";
UPDATE TypeProperties SET Value = 30
WHERE Name = 'DARK_AGE_CITIES_LOST_PLAYER' AND Type = "DIFFICULTY_EMPEROR";
UPDATE TypeProperties SET Value = 35
WHERE Name = 'DARK_AGE_CITIES_LOST_PLAYER' AND Type = "DIFFICULTY_IMMORTAL";
UPDATE TypeProperties SET Value = 40
WHERE Name = 'DARK_AGE_CITIES_LOST_PLAYER' AND Type = "DIFFICULTY_DEITY";
UPDATE TypeProperties SET Value = 30
WHERE Name = 'DARK_AGE_CITIES_LOST_AI' AND Type = "DIFFICULTY_SETTLER";
UPDATE TypeProperties SET Value = 30
WHERE Name = 'DARK_AGE_CITIES_LOST_AI' AND Type = "DIFFICULTY_CHIEFTAIN";
UPDATE TypeProperties SET Value = 25
WHERE Name = 'DARK_AGE_CITIES_LOST_AI' AND Type = "DIFFICULTY_WARLORD";
UPDATE TypeProperties SET Value = 20
WHERE Name = 'DARK_AGE_CITIES_LOST_AI' AND Type = "DIFFICULTY_PRINCE";
UPDATE TypeProperties SET Value = 15
WHERE Name = 'DARK_AGE_CITIES_LOST_AI' AND Type = "DIFFICULTY_KING";
UPDATE TypeProperties SET Value = 15
WHERE Name = 'DARK_AGE_CITIES_LOST_AI' AND Type = "DIFFICULTY_EMPEROR";
UPDATE TypeProperties SET Value = 10
WHERE Name = 'DARK_AGE_CITIES_LOST_AI' AND Type = "DIFFICULTY_IMMORTAL";
UPDATE TypeProperties SET Value = 10
WHERE Name = 'DARK_AGE_CITIES_LOST_AI' AND Type = "DIFFICULTY_DEITY";

--黄金时代政策
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_HEARTBEAT_OF_STEAM' AND ModifierId='GOLDEN_CITIES_PRODUCTION_STACKING';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_HEARTBEAT_OF_STEAM' AND ModifierId='GOLDEN_HEARTBEAT_OF_STEAM_INDUSTRIAL_GOLD';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_MILITARY_INDUSTRIAL_COMPLEX' AND ModifierId='GOLDEN_POLICY_MILITARY_INDUSTRIAL_COMPLEX_HORSES';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_MILITARY_INDUSTRIAL_COMPLEX' AND ModifierId='GOLDEN_POLICY_MILITARY_INDUSTRIAL_COMPLEX_IRON';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_MILITARY_INDUSTRIAL_COMPLEX' AND ModifierId='GOLDEN_POLICY_MILITARY_INDUSTRIAL_COMPLEX_NITER';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_MILITARY_INDUSTRIAL_COMPLEX' AND ModifierId='GOLDEN_POLICY_MILITARY_INDUSTRIAL_COMPLEX_COAL';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_FREE_ENQUIRY' AND ModifierId='GOLDEN_CITIES_SCIENCE_STACKING';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_CULTURE_INDUSTRY' AND ModifierId='GOLDEN_CITIES_CULTURE_STACKING';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_CULTURE_INDUSTRY' AND ModifierId='GOLDEN_CULTURE_INDUSTRY_THEATER_GOLD';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_SKY_AND_STARS' AND ModifierId='GOLDEN_SKY_AND_STARS_SPACE_RACE_PROJECTS_PRODUCTION';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_PRAETORIAN_GUARD' AND ModifierId='GOLDEN_PRAETORIAN_GUARD_COMBAT_STENGTH';

INSERT OR REPLACE INTO PolicyModifiers 
(PolicyType,                           	ModifierId)VALUES	
('POLICY_HEARTBEAT_OF_STEAM',          	'POLICY_HEARTBEAT_OF_STEAM_GA_INDUSTRIALINFORMATION'),
('POLICY_HEARTBEAT_OF_STEAM',          	'POLICY_HEARTBEAT_OF_STEAM_GA_CAMPUS'),
('POLICY_FREE_ENQUIRY',                	'POLICY_FREE_ENQUIRY_GA_HARBOR'),
('POLICY_FREE_ENQUIRY',                	'POLICY_FREE_ENQUIRY_GA_COMMERCIAL_HUB'),
('POLICY_CULTURE_INDUSTRY',            	'POLICY_CULTURE_INDUSTRY_GA_CULTURE_DISTRICT'),
('POLICY_CULTURE_INDUSTRY',            	'POLICY_CULTURE_INDUSTRY_GA_PURCHASE_ENTERTAINMENT_COMPLEX'),
('POLICY_CULTURE_INDUSTRY',            	'POLICY_CULTURE_INDUSTRY_GA_PURCHASE_WATER_PARK'),
-- ('POLICY_CULTURE_INDUSTRY',            	'POLICY_CULTURE_INDUSTRY_GA_PRODUCTION_DISTRICT'),--BUG
('POLICY_MONUMENTALITY',            	'POLICY_MONUMENTALITY_GA_MOVEMENT_SETTLER'),
('POLICY_MONUMENTALITY',            	'POLICY_MONUMENTALITY_GA_BUILDER_DISCOUNT_MODIFIER'),
('POLICY_SKY_AND_STARS',            	'POLICY_PRODUCTION_TO_SPACEPORTS'),
('POLICY_SKY_AND_STARS',               	'POLICY_PRODUCTION_TO_AERODROMES'),
('POLICY_PRAETORIAN_GUARD',             'POLICY_PRAETORIAN_GUARD_GA_HEALING'),
('POLICY_PRAETORIAN_GUARD',             'POLICY_PRAETORIAN_GUARD_GA_PRODUCTION_ENCAMPMENT'),
('POLICY_PRAETORIAN_GUARD',             'POLICY_PRAETORIAN_GUARD_GA_PRODUCTION_BARRACKS'),
('POLICY_PRAETORIAN_GUARD',             'POLICY_PRAETORIAN_GUARD_GA_PRODUCTION_STABLE'),
('POLICY_PRAETORIAN_GUARD',             'POLICY_PRAETORIAN_GUARD_GA_PRODUCTION_ARMORY'),
('POLICY_PRAETORIAN_GUARD',             'POLICY_PRAETORIAN_GUARD_GA_PRODUCTION_MILITARY_ACADEMY');

--黑暗时代政策（来自动荡模式）
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_SAMODERZHAVIYE' ;
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_ISOLATIONISM' AND ModifierId='GOLDEN_ISOLATIONISM_DOMESTIC_TRADE_ROUTE_FAITH';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_ISOLATIONISM' AND ModifierId='GOLDEN_ISOLATIONISM_DOMESTIC_TRADE_ROUTE_SCIENCE';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_ISOLATIONISM' AND ModifierId='GOLDEN_ISOLATIONISM_DOMESTIC_TRADE_ROUTE_CULTURE';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_COLLECTIVISM' AND ModifierId='COLLECTIVISM_INDUSTRIAL_ADJACENCY';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_COLLECTIVISM' AND ModifierId='COLLECTIVISM_FARM_FOOD';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_DECENTRALIZATION';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_DESPOTIC_PATERNALISM';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_ROBBER_BARONS' AND ModifierId='GOLDEN_ROBBER_BARONS_GOLD_PLUS';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_ROBBER_BARONS' AND ModifierId='GOLDEN_ROBBER_BARONS_PRODUCTION_PLUS';

INSERT OR REPLACE INTO PolicyModifiers 
(PolicyType,                           	ModifierId)VALUES	
('POLICY_SAMODERZHAVIYE',          		'SAMODERZHAVIYE_CAPITAL_PRODUCTION'),
('POLICY_SAMODERZHAVIYE',          		'SAMODERZHAVIYE_GOVERNOR_NEUTRALIZE'),
('POLICY_COLLECTIVISM',          		'COLLECTIVISM_ADD_HOUSING'),
('POLICY_DECENTRALIZATION',          	'DECENTRALIZATION_LOWPOP_LOYALTY'),
('POLICY_DECENTRALIZATION',          	'DECENTRALIZATION_HIGHPOP_GOLD'),
('POLICY_DESPOTIC_PATERNALISM',          'DESPOTIC_PATERNALISM_LOYALTY'),
('POLICY_DESPOTIC_PATERNALISM',          'DESPOTIC_PATERNALISM_SCIENCE'),
('POLICY_DESPOTIC_PATERNALISM',          'DESPOTIC_PATERNALISM_CULTURE');

UPDATE ModifierArguments SET Value = 10
WHERE ModifierId = 'SOFTTARGETS_COMBAT_STENGTH_DEFENDING_CITIES' AND Name = 'Amount';
UPDATE ModifierArguments SET Value = 10
WHERE ModifierId = 'SOFTTARGETS_COMBAT_STENGTH_ATTACKING_DISTRICTS' AND Name = 'Amount';
UPDATE ModifierArguments SET Value = -3
WHERE ModifierId = 'SOFTTARGETS_COMBAT_STENGTH_ATTACKING_UNITS' AND Name = 'Amount';
UPDATE ModifierArguments SET Value = 50
WHERE ModifierId = 'ROBBERBARONS_BANK_OR_SHIPYARD_GOLD' AND Name = 'Amount';
UPDATE ModifierArguments SET Value = 25
WHERE ModifierId = 'ROBBERBARONS_BANK_OR_SHIPYARD_PRODUCTION' AND Name = 'Amount';

--黑暗时代政策（来自迭起兴衰）
UPDATE Policies SET Description = 'LOC_POLICY_AUTOMATED_WORKFORCE_DESCRIPTION'
WHERE PolicyType = 'POLICY_AUTOMATED_WORKFORCE';
UPDATE Policies SET Description = 'LOC_POLICY_CYBER_WARFARE_DESCRIPTION'
WHERE PolicyType = 'POLICY_CYBER_WARFARE';
UPDATE Policies SET Description = 'LOC_POLICY_DISINFORMATION_CAMPAIGN_DESCRIPTION'
WHERE PolicyType = 'POLICY_DISINFORMATION_CAMPAIGN';
UPDATE Policies SET Description = 'LOC_POLICY_ROGUE_STATE_DESCRIPTION'
WHERE PolicyType = 'POLICY_ROGUE_STATE';
UPDATE Policies SET Description = 'LOC_POLICY_ELITE_FORCES_DA_DESCRIPTION'
WHERE PolicyType = 'POLICY_ELITE_FORCES';
UPDATE Policies SET Description = 'LOC_POLICY_FLOWER_POWER_DESCRIPTION'
WHERE PolicyType = 'POLICY_FLOWER_POWER';
UPDATE Policies SET Description = 'LOC_POLICY_INQUISITION_DA_DESCRIPTION'
WHERE PolicyType = 'POLICY_INQUISITION';
UPDATE Policies SET Description = 'LOC_POLICY_MONASTICISM_DA_DESCRIPTION'
WHERE PolicyType = 'POLICY_MONASTICISM';

DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_CYBER_WARFARE' AND ModifierId='GOLDEN_CYBER_WARFARE_ESPIONAGE_ESTABLISH';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_CYBER_WARFARE' AND ModifierId='GOLDEN_CYBER_WARFARE_ESPIONAGE_REDUCTION';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_DISINFORMATION_CAMPAIGN' AND ModifierId='GOLDEN_DISINFORMATION_CAMPAIGN_SPY_DEFENSE';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_ROGUE_STATE' AND ModifierId='GOLDEN_ROGUE_STATE_NO_WMD_MAINTENANCE';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_ELITE_FORCES' AND ModifierId='GOLDEN_ELITE_FORCES_COMBAT_STENGTH';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_FLOWER_POWER' AND ModifierId='FUTURE_VICTORY_CULTURE_ROCK_BAND_PROMOTIONS';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_INQUISITION' AND ModifierId='GOLDEN_INQUISITION_FAITH_MODIFIER';
DELETE FROM PolicyModifiers WHERE PolicyType='POLICY_MONASTICISM';
INSERT OR REPLACE INTO PolicyModifiers 
(PolicyType,                           	ModifierId)VALUES	
('POLICY_AUTOMATED_WORKFORCE',          'AUTOMATED_WORKFORCE_LOYALTY_LOSS'),
('POLICY_MONASTICISM',          		'MONASTICISM_HOLYSITE_SCIENCE'),
('POLICY_MONASTICISM',          		'MONASTICISM_CULTURE_MODIFIER');

UPDATE ModifierArguments SET Value = 20
WHERE ModifierId = 'AUTOMATED_WORKFORCE_PROJECT_PRODUCTION' AND Name = 'Amount';
UPDATE ModifierArguments SET Value = 3
WHERE ModifierId = 'DISINFORMATION_CAMPAIGN_BROADCAST_FAVOR' AND Name = 'Amount';
UPDATE ModifierArguments SET Value = -10
WHERE ModifierId = 'DISINFORMATION_CAMPAIGN_SCIENCE_REDUCTION' AND Name = 'Amount';
UPDATE ModifierArguments SET Value = -10
WHERE ModifierId = 'DISINFORMATION_CAMPAIGN_CULTURE_REDUCTION' AND Name = 'Amount';
UPDATE ModifierArguments SET Value = 100
WHERE ModifierId = 'ROGUESTATE_MANHATTANPROJECT_PRODUCTION' AND Name = 'Amount'; 
UPDATE ModifierArguments SET Value = 50
WHERE ModifierId = 'ROGUESTATE_PROJECTIVY_PRODUCTION' AND Name = 'Amount';
UPDATE ModifierArguments SET Value = 50
WHERE ModifierId = 'ROGUESTATE_NUCLEARDEVICE_PRODUCTION' AND Name = 'Amount';
UPDATE ModifierArguments SET Value = 50
WHERE ModifierId = 'ROGUESTATE_THERMONUCLEARDEVICE_PRODUCTION' AND Name = 'Amount';
UPDATE ModifierArguments SET Value = -2
WHERE ModifierId = 'ELITEFORCES_EXTRA_MAINTENANCE' AND Name = 'Amount';
UPDATE ModifierArguments SET Value = -100
WHERE ModifierId = 'FLOWER_POWER_PURCHASE_INCREASE' AND Name = 'Amount';
UPDATE ModifierArguments SET Value = -100
WHERE ModifierId = 'FLOWER_POWER_PRODUCTION_INCREASE' AND Name = 'Amount';
UPDATE ModifierArguments SET Value = -25
WHERE ModifierId = 'INQUISITION_SCIENCE_MODIFIER' AND Name = 'Amount';