--CIVILIZATION_AZTEC
UPDATE Buildings SET Entertainment = 2, Cost = 80, CitizenSlots = 1, Maintenance = 2, RegionalRange = 3
WHERE BuildingType = 'BUILDING_TLACHTLI' AND EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_TLACHTLI');

INSERT OR REPLACE INTO Building_CitizenYieldChanges (BuildingType, YieldType, YieldChange)
SELECT	'BUILDING_TLACHTLI', 'YIELD_CULTURE', 1 WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_TLACHTLI');
-- INSERT OR REPLACE INTO Building_CitizenYieldChanges (BuildingType, YieldType, YieldChange)
-- SELECT	'BUILDING_TLACHTLI', 'YIELD_GOLD', 1 WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_TLACHTLI');
INSERT OR REPLACE INTO Building_CitizenYieldChanges (BuildingType, YieldType, YieldChange)
SELECT	'BUILDING_TLACHTLI', 'YIELD_FAITH', 1 WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_TLACHTLI');
-- INSERT OR REPLACE INTO Building_CitizenYieldChanges (BuildingType, YieldType, YieldChange)
-- SELECT	'BUILDING_TLACHTLI', 'YIELD_SCIENCE', 1 WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_TLACHTLI');

UPDATE Building_GreatPersonPoints SET PointsPerTurn = 3
WHERE BuildingType = 'BUILDING_TLACHTLI' AND GreatPersonClassType = 'GREAT_PERSON_CLASS_GENERAL' AND EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_TLACHTLI');

INSERT OR REPLACE INTO BuildingModifiers(BuildingType, ModifierId)
SELECT	'BUILDING_TLACHTLI', 'GOLDEN_ARENA_TOURISM' WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_TLACHTLI');

--CIVILIZATION_KHMER
--CIVILIZATION_INDONESIA
UPDATE Buildings SET Cost = 100, Maintenance = 3, CitizenSlots = 1, RegionalRange = 4
WHERE BuildingType = 'BUILDING_PRASAT' AND EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_PRASAT');

INSERT OR REPLACE INTO Building_CitizenYieldChanges		(BuildingType, YieldType, YieldChange)
SELECT	'BUILDING_PRASAT', 'YIELD_FAITH', 1 WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_PRASAT');

--CIVILIZATION_MACEDON
--CIVILIZATION_PERSIA
UPDATE Buildings SET Cost = 50, Housing = 2
WHERE BuildingType = 'BUILDING_BASILIKOI_PAIDES' AND EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_BASILIKOI_PAIDES');

DELETE FROM Building_YieldChanges WHERE BuildingType = 'BUILDING_BASILIKOI_PAIDES'AND YieldType = 'YIELD_PRODUCTION' AND EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_BASILIKOI_PAIDES');

INSERT OR REPLACE INTO Building_CitizenYieldChanges (BuildingType, YieldType, YieldChange)
SELECT	'BUILDING_BASILIKOI_PAIDES', 'YIELD_SCIENCE', 1 WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_BASILIKOI_PAIDES');
INSERT OR REPLACE INTO Building_CitizenYieldChanges (BuildingType, YieldType, YieldChange)
SELECT	'BUILDING_BASILIKOI_PAIDES', 'YIELD_PRODUCTION', 1 WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_BASILIKOI_PAIDES');

--CIVILIZATION_POLAND
UPDATE Buildings SET Cost = 80, RegionalRange = 3
WHERE BuildingType = 'BUILDING_SUKIENNICE' AND EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_SUKIENNICE');

UPDATE Building_YieldChanges SET YieldChange = 4
WHERE BuildingType = 'BUILDING_SUKIENNICE' AND YieldType = 'YIELD_GOLD' AND EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_SUKIENNICE');

INSERT OR REPLACE INTO Buildings_XP2(BuildingType, RequiredPower)
SELECT	'BUILDING_SUKIENNICE', 1 WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_SUKIENNICE');

INSERT OR REPLACE INTO Building_YieldChangesBonusWithPower(BuildingType, YieldType, YieldChange)
SELECT	'BUILDING_SUKIENNICE', 'YIELD_GOLD', 4 WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_SUKIENNICE');

INSERT OR REPLACE INTO Building_CitizenYieldChanges(BuildingType, YieldType, YieldChange)
SELECT	'BUILDING_SUKIENNICE', 'YIELD_GOLD', 1 WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_SUKIENNICE');

--CIVILIZATION_BABYLON
UPDATE Buildings SET Housing = 2
WHERE BuildingType = 'BUILDING_PALGUM' AND EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_PALGUM');

INSERT OR REPLACE INTO Building_YieldChanges		(BuildingType, YieldType, YieldChange)
SELECT	'BUILDING_PALGUM', 'YIELD_FOOD', 1 WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_PALGUM');
UPDATE Building_YieldChanges SET YieldChange = 1
WHERE BuildingType = 'BUILDING_PALGUM' AND YieldType = 'YIELD_PRODUCTION' AND EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_PALGUM');

--CIVILIZATION_PORTUGAL
UPDATE Buildings SET Housing = 0, Cost = 180, Maintenance = 3, RegionalRange = 4
WHERE BuildingType = 'BUILDING_NAVIGATION_SCHOOL' AND EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_NAVIGATION_SCHOOL');

UPDATE Building_YieldChanges SET YieldChange = 4
WHERE BuildingType = 'BUILDING_NAVIGATION_SCHOOL' AND YieldType = 'YIELD_SCIENCE' AND EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_NAVIGATION_SCHOOL');

INSERT OR REPLACE INTO Buildings_XP2(BuildingType, RequiredPower)
SELECT	'BUILDING_NAVIGATION_SCHOOL', 2 WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_NAVIGATION_SCHOOL');

INSERT OR REPLACE INTO Building_YieldChangesBonusWithPower(BuildingType, YieldType, YieldChange)
SELECT	'BUILDING_NAVIGATION_SCHOOL', 'YIELD_SCIENCE', 4 WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_NAVIGATION_SCHOOL');

INSERT OR REPLACE INTO Building_CitizenYieldChanges(BuildingType, YieldType, YieldChange)
SELECT	'BUILDING_NAVIGATION_SCHOOL', 'YIELD_SCIENCE', 1 WHERE EXISTS (SELECT * FROM Buildings WHERE BuildingType='BUILDING_NAVIGATION_SCHOOL');
