--BUG修复
--CIVILIZATION_MAYA
--DISTRICT_OBSERVATORY
DELETE FROM District_CitizenYieldChanges WHERE DistrictType = 'DISTRICT_OBSERVATORY' AND NOT EXISTS (SELECT * FROM Units WHERE UnitType = 'UNIT_MAYAN_HULCHE');
INSERT OR REPLACE INTO District_CitizenYieldChanges (DistrictType, YieldType, YieldChange)
SELECT	'DISTRICT_OBSERVATORY', 'YIELD_SCIENCE', 4 WHERE EXISTS (SELECT * FROM Units WHERE UnitType = 'UNIT_MAYAN_HULCHE');
INSERT OR REPLACE INTO District_CitizenYieldChanges (DistrictType, YieldType, YieldChange)
SELECT	'DISTRICT_OBSERVATORY', 'YIELD_FOOD', -1 WHERE EXISTS (SELECT * FROM Units WHERE UnitType = 'UNIT_MAYAN_HULCHE');
