------
--UA--
------
--TraitModifiers
DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_CIVILIZATION_SATRAPIES';
INSERT OR REPLACE INTO TraitModifiers (TraitType, 			ModifierId) VALUES	
('TRAIT_CIVILIZATION_SATRAPIES',	'TRAIT_SATRAPIES_IMPROVED_ROUTE_LEVEL'),--Base game
('TRAIT_CIVILIZATION_SATRAPIES',	'GOLDEN_TRAIT_GOLD_PURCHASE_DISTRICTS'),--v223 GoldenAge
('TRAIT_CIVILIZATION_SATRAPIES',	'GA_TRAIT_SATRAPIES_CITY_GOVERNOR_TITLE'),
('TRAIT_CIVILIZATION_SATRAPIES',	'GA_TRAIT_SATRAPIES_DOMESTIC_TRADE_ROUTE_CULTURE_PER_SPECIALTY_DISTRICT'),
('TRAIT_CIVILIZATION_SATRAPIES',	'GA_TRAIT_SATRAPIES_DOMESTIC_TRADE_ROUTE_GOLD_PER_SPECIALTY_DISTRICT');
INSERT OR REPLACE INTO TraitModifiers (TraitType, ModifierId)
SELECT	'TRAIT_CIVILIZATION_SATRAPIES', 'GOLDEN_TRAIT_SATRAPIES_DEBUFF_INTERNATIONAL_TRADE_ROUTE' ||YieldType FROM Yields;

----Modifiers
INSERT OR REPLACE INTO Modifiers (ModifierId, 					ModifierType, 												RunOnce, 	Permanent, 	SubjectRequirementSetId) VALUES
('GA_TRAIT_SATRAPIES_CITY_GOVERNOR_TITLE',						'MODIFIER_PLAYER_CITIES_ATTACH_MODIFIER',					0,			0,			NULL),
('GA_TRAIT_SATRAPIES_CITY_GOVERNOR_TITLE_MODIFIER',				'MODIFIER_PLAYER_ADJUST_GOVERNOR_POINTS',					1,			1,			NULL),
('GA_TRAIT_SATRAPIES_DOMESTIC_TRADE_ROUTE_CULTURE_PER_SPECIALTY_DISTRICT',					'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_PER_SPECIALTY_DISTRICT_FOR_DOMESTIC',					0,			0,			NULL),
('GA_TRAIT_SATRAPIES_DOMESTIC_TRADE_ROUTE_GOLD_PER_SPECIALTY_DISTRICT',						'MODIFIER_PLAYER_ADJUST_TRADE_ROUTE_YIELD_PER_SPECIALTY_DISTRICT_FOR_DOMESTIC',					0,			0,			NULL);
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, SubjectRequirementSetId)
SELECT	'GOLDEN_TRAIT_SATRAPIES_DEBUFF_INTERNATIONAL_TRADE_ROUTE' ||YieldType, 'GOLDEN_MODIFIER_PLAYER_ADJUST_INTERNATIONAL_TRADE_ROUTE_YIELD_MODIFIER', NULL FROM Yields;

--ModifierArguments
INSERT OR REPLACE INTO ModifierArguments (ModifierId,				    	Name,		    Value) VALUES
('GA_TRAIT_SATRAPIES_CITY_GOVERNOR_TITLE',									'ModifierId',	'GA_TRAIT_SATRAPIES_CITY_GOVERNOR_TITLE_MODIFIER'),
('GA_TRAIT_SATRAPIES_CITY_GOVERNOR_TITLE_MODIFIER',							'Delta',		1),
('GA_TRAIT_SATRAPIES_DOMESTIC_TRADE_ROUTE_CULTURE_PER_SPECIALTY_DISTRICT',	'YieldType',	'YIELD_CULTURE'),
('GA_TRAIT_SATRAPIES_DOMESTIC_TRADE_ROUTE_CULTURE_PER_SPECIALTY_DISTRICT',	'Amount',		1),
('GA_TRAIT_SATRAPIES_DOMESTIC_TRADE_ROUTE_GOLD_PER_SPECIALTY_DISTRICT',		'YieldType',	'YIELD_GOLD'),
('GA_TRAIT_SATRAPIES_DOMESTIC_TRADE_ROUTE_GOLD_PER_SPECIALTY_DISTRICT',		'Amount',		1);

INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_TRAIT_SATRAPIES_DEBUFF_INTERNATIONAL_TRADE_ROUTE' ||YieldType, 'YieldType', YieldType 	FROM Yields;
INSERT OR REPLACE INTO ModifierArguments (ModifierId, Name, Value)
SELECT	'GOLDEN_TRAIT_SATRAPIES_DEBUFF_INTERNATIONAL_TRADE_ROUTE' ||YieldType, 'Amount', 	-50 		FROM Yields;

------
--LA--
------
--TraitModifiers
DELETE FROM TraitModifiers WHERE TraitType = 'TRAIT_LEADER_FALL_BABYLON' AND ModifierId = 'TRAIT_FALLBABYLON_WARMONGER_MAX';
INSERT OR REPLACE INTO TraitModifiers (TraitType, 			ModifierID) VALUES	
('TRAIT_LEADER_FALL_BABYLON',	'GOLDEN_TRAIT_FALL_BABYLON_FREE_MELEE_UNITS');
----Modifiers
INSERT OR REPLACE INTO Modifiers (ModifierId, ModifierType, RunOnce, Permanent, SubjectRequirementSetId) VALUES	
('GOLDEN_TRAIT_FALL_BABYLON_FREE_MELEE_UNITS',         'MODIFIER_PLAYER_CITIES_GRANT_UNIT_BY_CLASS',        0, 0, 'CITY_NOT_FOUNDED');
--ModifierArguments
INSERT OR REPLACE INTO ModifierArguments (ModifierId,			Name,		        Value) VALUES
('GOLDEN_TRAIT_FALL_BABYLON_FREE_MELEE_UNITS',					'UnitPromotionClassType',	    'PROMOTION_CLASS_MELEE');

UPDATE ModifierArguments SET Value = 8 WHERE ModifierId = 'TRAIT_ADDITIONAL_MARTIAL_LAW';