--v223版有之前的改动
DELETE FROM BuildingModifiers WHERE BuildingType = 'BUILDING_ALCHEMICAL_SOCIETY' AND ModifierId = 'GOLDEN_POPULATION_SCIENCE';
--v226 地脉山脉
DELETE FROM Resource_ValidTerrains WHERE ResourceType = 'RESOURCE_LEY_LINE';
INSERT OR REPLACE INTO Resource_ValidTerrains
(ResourceType, TerrainType) VALUES 
('RESOURCE_LEY_LINE',  'TERRAIN_GRASS_MOUNTAIN'),
('RESOURCE_LEY_LINE',  'TERRAIN_PLAINS_MOUNTAIN'),
('RESOURCE_LEY_LINE',  'TERRAIN_DESERT_MOUNTAIN'),
('RESOURCE_LEY_LINE',  'TERRAIN_TUNDRA_MOUNTAIN');
UPDATE Resources SET Frequency = 50 WHERE ResourceType = 'RESOURCE_LEY_LINE';
--v226 邪教徒
UPDATE ModifierArguments SET Value = 30 WHERE ModifierId = 'SPREAD_DISSENT_LOYALTY_DAMAGE' AND NAME = 'Amount';
UPDATE Units_MODE SET ActionCharges = 1 WHERE UnitType = 'UNIT_CULTIST';
