INSERT OR REPLACE INTO Building_GreatWorks
(BuildingType,							GreatWorkSlotType,			NumSlots)		VALUES
-- ('BUILDING_BANK',						'GREATWORKSLOT_PRODUCT',	1),
-- ('BUILDING_GRAND_BAZAAR',				'GREATWORKSLOT_PRODUCT',	1),
-- ('BUILDING_COMMERCIAL',					'GREATWORKSLOT_PRODUCT',	1),
-- ('BUILDING_GILDED_VAULT',				'GREATWORKSLOT_PRODUCT',	1),
-- ('BUILDING_TAX_BUREAU',					'GREATWORKSLOT_PRODUCT',	1),
('BUILDING_URBAN_CONSTRUCTION',			'GREATWORKSLOT_PRODUCT',	2),
('BUILDING_MILITARY_CORP',				'GREATWORKSLOT_PRODUCT',	2),
('BUILDING_STOCK_EXCHANGE',				'GREATWORKSLOT_PRODUCT',	2),
('BUILDING_LUXURY_GOODS',				'GREATWORKSLOT_PRODUCT',	1),
('BUILDING_DIGITAL_CURRENCY',			'GREATWORKSLOT_PRODUCT',	1),
('BUILDING_FINANCIAL_TOWER',			'GREATWORKSLOT_PRODUCT',	1),
('BUILDING_MINING_GROUP',				'GREATWORKSLOT_PRODUCT',	1);